
environments:
  default:
    values:
      - env/vietnam.yaml
  indonesia:
    values:
      - env/indonesia.yaml
  oc:
    values:
      - env/oc.yaml

releases:

  - name: nginx-ingress
    namespace: default
    chart: ingress-nginx/ingress-nginx
    version: ~3.8.0

  - name: vietnam-ecr-token
    namespace: okc
    chart: ../helm/ecr-token
    version: ~0.1.0
    values:
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

  - name: vietnam-sfu
    namespace: okc
    chart: ../helm/sfu
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - hostNetworking: true
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - sfuManagerConfiguration:
          promHost: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

  - name: vietnam-sfu-gateway
    namespace: okc
    chart: ../helm/sfu-gateway
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.domain }}
                secretName: "letsencrypt-live{{ .Values.domain }}"
          hosts:
            - host: live{{ .Values.domain }}
              paths:
                - "/sfu"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi


  - name: vietnam-static
    namespace: okc
    chart: ../helm/static
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.domain }}
                secretName: "letsencrypt-live{{ .Values.domain }}"
          hosts:
            - host: live{{ .Values.domain }}
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi

  - name: vietnam-hub
    namespace: okc
    chart: ../helm/hub
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - hub{{ .Values.domain }}
                secretName: "letsencrypt-hub{{ .Values.domain }}"
          hosts:
            - host: hub{{ .Values.domain }}
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi

  - name: vietnam-live
    namespace: okc
    chart: ../helm/live
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.domain }}
                secretName: "letsencrypt-live{{ .Values.domain }}"
          hosts:
            - host: live{{ .Values.domain }}
              paths:
                - "/graphql"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  - name: vietnam-user-service
    namespace: okc
    chart: ../helm/user-service
    values:
      - image:
          repository: 494634321140.dkr.ecr.ap-northeast-2.amazonaws.com/vietnam-user-service-guy
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - api{{ .Values.domain }}
                secretName: "letsencrypt-api{{ .Values.domain }}"
          hosts:
            - host: live{{ .Values.domain }}
              paths:
                - "/user"

  - name: vietnam-kl2
    namespace: okc
    chart: ../helm/kl2
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - kl2{{ .Values.domain }}
                secretName: "letsencrypt-kl2{{ .Values.domain }}"
          hosts:
            - host: kl2{{ .Values.domain }}
              paths:
                - "/"
      - configuration:
          connection_string: "dbc_yyd:xxxxxx@tcp(mysql-primary.persistence:3306)/kidsloop2?parseTime: true&charset: utf8mb4"

