apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : {{ .Values.gcp.project }}
  name: "{{ .Values.gcp.redis_name }}"
spec:
  displayName: {{ .Values.gcp.redis_display_name }}
  memorySizeGb: {{ .Values.gcp.redis_memory_size }}
  authorizedNetworkRef:
    external: "{{ .Values.gcp.network }}"
  redisVersion:  "{{ .Values.gcp.redis_version }}"
  region: "{{ .Values.gcp.region }}"
  tier: "{{ .Values.gcp.redis_tier }}"

