nameOverride: ""
fullnameOverride: ""
replicaCount: 1
imagePullSecrets: []


image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-h5p-xapi-service
  pullPolicy: Always
  tag: latest

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]
  
resources: {}

sqlProxy:
  resources:
      # The proxy's memory use scales linearly with the number of active
      # connections. Fewer open connections will use less memory. Adjust
      # this value based on your application's requirements.
      # The proxy's CPU use scales linearly with the amount of IO between
      # the database and the application. Adjust this value based on your
      # application's requirements.
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
      
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80