nameOverride: ""
fullnameOverride: ""
replicaCount: 1
imagePullSecrets: []


image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-h5p-xapi-service
  pullPolicy: Always
  tag: latest

ingress:
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt"
  }
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]
  
resources: {}

