{
 "title": "Kidsloop Environment Overview",
 "description": "Details about the environment",
 "tags": [ "kidsloop" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Domain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_ingress_controller_ssl_expire_time_seconds{host=~\"hub.*\"}"
    }
   ]
  },
  {
   "title": "Special Role Access",
   "type": "table",
   "description": "These users have special privileges in the environment",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (email, org, role) (kl_super_admin_count)"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(kl_total_users_count)" }
   ]
  },
  {
   "title": "Internal Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(kl_internal_users_count)" }
   ]
  },
  {
   "title": "Organizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kl_entity_count{entity=\"organization\"})"
    }
   ]
  },
  {
   "title": "Schools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kl_entity_count{entity=\"school\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing [by severity]",
   "type": "gauge",
   "description": "How many alerts are currently firing in Prometheus",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (severity) (ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Alerts by Name",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (alertname) (ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Alerts by Severity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (severity) (ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "Users in environment",
   "type": "graph",
   "description": "Tracks the number of users stored in the database",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kl_total_users_count)", "legendFormat": "Total" },
    {
     "expr": "sum(kl_internal_users_count)",
     "legendFormat": "Internal (@calmid.com | @kidsloop.live)"
    },
    { "expr": "sum(kl_external_users_count)", "legendFormat": "External" }
   ]
  },
  {
   "title": "Database Entity Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kl_entity_count{entity=\"class\"})",
     "legendFormat": "classes"
    },
    {
     "expr": "sum(kl_entity_count{entity=\"school\"})",
     "legendFormat": "schools"
    },
    {
     "expr": "sum(kl_entity_count{entity=\"organization\"})",
     "legendFormat": "organizations"
    },
    {
     "expr": "sum(kl_entity_count{entity=\"program\"})",
     "legendFormat": "programs"
    },
    {
     "expr": "sum(kl_entity_count{entity=\"category\"})",
     "legendFormat": "categories"
    },
    {
     "expr": "sum(kl_entity_count{entity=\"subcategory\"})",
     "legendFormat": "subcategories"
    }
   ]
  }
 ]
}