{
 "title": "Kidsloop Cluster logs overview",
 "tags": [
  "kidsloop",
  "logs",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container", "label": "Container", "query": "label_values(container)" },
   { "name": "level", "label": "Level", "query": "label_values(level)" },
   { "name": "source_code", "label": "Source", "query": "label_values(source_code)" },
   { "name": "regex_query", "label": "Log Query (regex)" }
  ]
 },
 "panels": [
  {
   "title": "Log Error Rates by container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({level=~\"warning|warn|error|WARN|WARNING|ERROR|ERR\"}[10m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Log Error Rates by source line",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (source_code) (count_over_time({level=~\"warning|warn|error|WARN|WARNING|ERROR|ERR\"}[10m]))",
     "legendFormat": "{{source_code}}"
    }
   ]
  },
  {
   "title": "Log lines",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{level=~\"$level\", container=~\"$container\"} |~ \"$regex_query\"",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}