{
 "title": "CMS Backend",
 "description": "CMS backend dashboard",
 "tags": [
  "kidsloop",
  "cms"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "breakdown",
    "label": "Breakdown",
    "query": "level, path, method, status, source_code, stream, type"
   },
   {
    "name": "log_format",
    "label": "Log format",
    "query": " raw :   , plain : | json | line_format \"{{.M}}\""
   },
   { "name": "level", "label": "Level", "query": "label_values(level)" }
  ]
 },
 "panels": [
  {
   "title": "Log rate (by $breakdown)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "repeat": "breakdown",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"}[$__interval])) by ($breakdown)",
     "legendFormat": "{{$breakdown}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\", level=~\"ERROR|WARN\"}[$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "Log rate (by $breakdown)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"}[$__interval])) by ($breakdown)",
     "legendFormat": "{{$breakdown}}"
    }
   ]
  },
  {
   "title": "CMS Backend Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"} $log_format"
    }
   ]
  },
  {
   "title": "Log rate (by $breakdown)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"}[$__interval])) by ($breakdown)",
     "legendFormat": "{{$breakdown}}"
    }
   ]
  },
  {
   "title": "Log rate (by $breakdown)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"}[$__interval])) by ($breakdown)",
     "legendFormat": "{{$breakdown}}"
    }
   ]
  },
  {
   "title": "Log rate (by $breakdown)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"}[$__interval])) by ($breakdown)",
     "legendFormat": "{{$breakdown}}"
    }
   ]
  },
  {
   "title": "Log rate (by $breakdown)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"}[$__interval])) by ($breakdown)",
     "legendFormat": "{{$breakdown}}"
    }
   ]
  },
  {
   "title": "Log rate (by $breakdown)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app_kubernetes_io_instance=\"cms-backend\",container=\"cms-backend\",level=~\"$level\"}[$__interval])) by ($breakdown)",
     "legendFormat": "{{$breakdown}}"
    }
   ]
  }
 ]
}