apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : PROJECT_ID
  name: BUCKET_NAME
spec:
  displayName: "kidsloop"
  memorySizeGb: 1
  authorizedNetworkRef: [network]
  redisVersion:  "REDIS_5_0"
  region: {{ .Values.gcp.region }}
  tier: "STANDARD_HA"

