apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: {{ include "atlas-cluster.projectfullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas-cluster.labels" . | nindent 4 }}
  annotations:
    'helm.sh/hook': post-delete,pre-install,pre-upgrade
spec:
  name: {{ .Values.project.atlasProjectName }}
  connectionSecretRef:
{{- if .Values.atlas.connectionSecretName }}
    name: {{ .Values.atlas.connectionSecretName}}
{{- else }}
    name: {{ include "atlas-cluster.fullname" . }}-secret
{{- end }}
  projectIpAccessList:
  {{- with .Values.project.projectIpAccessList }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
