replicaCount: 1

image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-auth-frontend
  pullPolicy: Always
  tag: seb-test-cors-sre-alpha-87

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt"
  }
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]

resources: {}

provider: "aws"

nodegroupSelector: {"nodegroup": "private"}

# backend config
timeoutSec: 30
cdn:
  enabled: false
connectionDraining:
  drainingTimeoutSec: 60
healthCheck:
  requestPath: /
  type: HTTP
  port: 80
  checkIntervalSec: 15
  timeoutSec: 15
  healthyThreshold: 1
  unhealthyThreshold: 2