apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgresql-backup-cronjob
  labels: 
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name  }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: postgresql-backup-serviceaccount
          imagePullSecrets:
            - name: ecr-registry-infra
          restartPolicy: OnFailure
          containers:
            - image: {{.Values.image}}
              imagePullPolicy: Always
              name: postgresql-backup
              volumeMounts:
                - name: s3-bucket-secret
                  mountPath: /root/.aws
                  readOnly: true              
              env:
                - name: POSTGRESQL_HOST
                  value: {{ .Values.postgresql_host }}
                - name: POSTGRESQL_USERNAME
                  value: {{ .Values.postgresql_username }}
                - name: POSTGRESQL_DATABASE
                  value: {{ .Values.postgresql_database }}
                - name: STORAGE_ENDPOINT
                  value: {{ .Values.storage_endpoint }}
                - name: STORAGE_REGION
                  value: {{ .Values.storage_region }}
                - name: STORAGE_BUCKET
                  value: {{ .Values.storage_bucket }}                                                                                          
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql
                      key: postgresql-password
          volumes:
            - name: s3-bucket-secret
              secret:
                secretName: "cms-backend-s3-secret"
  schedule: "0 1 * * *"
