apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresql-backup-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgresql-backup-role
subjects:
- kind: ServiceAccount
  name: postgresql-backup-serviceaccount
  namespace: {{ .Release.Namespace }}
