apiVersion: v1
kind: Service
metadata:
  name: {{ include "static.fullname" . }}-svc
  labels:
    {{- include "static.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "static.selectorLabels" . | nindent 4 }}
  type: ClusterIP
