environments:
  indonesia:
    values:
      - ../../../env/indonesia/.env.yaml
  oc:
    values:
      - ../../../env/oc/.env.yaml
      
releases:

  - name: gke-redis
    namespace: config-connector
    chart: ../charts/redis
    values:
      - gcp:
          region: {{ .Environment.Values.terraform_region }}
          network: {{ .Environment.Values.terraform_vpc.value }}
          project: {{ .Environment.Values.terraform_project }}


