pipelines:
  custom:
    sfu-manager:
    - step:
        name: 'Compile'
        image: golang:alpine
        script:
          - apk update && apk add upx
          - cd k8s/docker/service-sfu-manager
          - CGO_ENABLED=0 go build -ldflags="-s" -o ./vietnam-sfu-manager .
          - upx -9 -k ./vietnam-sfu-manager
        caches:
          - gomodules
        artifacts:
          - k8s/docker/service-sfu-manager/*

    - step:
        name: 'Build and push'
        image: python:3.7.4-alpine3.10
        script:
          - pip3 install -U awscli

          - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
          - export REPO=$DOCKER_REPO_URL/kidsloop-sfu-manager  # DOCKER_REPO_URL is workspace wide variable
        
          - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
      
          - cd k8s/docker/service-sfu-manager
          - docker build -t kidsloop-sfu-manager .
          
          - docker tag kidsloop-sfu-manager:latest $REPO:$BRANCH_TAG
          - docker tag kidsloop-sfu-manager:latest $REPO:$BRANCH_TAG-latest
          - docker tag kidsloop-sfu-manager:latest $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER

          - docker push $REPO:$BRANCH_TAG
          - docker push $REPO:$BRANCH_TAG-latest
          - docker push $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER
        
        services:
          - docker

        caches:
          - gomodules
    
definitions:
  caches:
    gomodules: vendor