image: public.ecr.aws/f2u4s3o8/helm:latest

clone:
  depth: 1

pipelines:
  pull-requests:
    '{*/vietnam/**}':
      - step:
          name: Helm Diff
          script:
            - echo "Deploy Production"

  branches:
    '{*/vietnam/**}':
      - step:
          name: Helm Diff
          script:
            - echo "Deploy Beta"
            - mkdir -p ~/.kube && chmod -R 700 ~/.kube
            - (umask  077 ; echo $KLVN_BETA | base64 --decode > ~/.kube/config)
            - kubectl get pods -n klvn-beta            