image: python:3.7.4-alpine3.10

pipelines:
  default:
    - step:
        name: "Build Nginx + push to ECR"
        script:
          - pip3 install -U awscli

          - aws configure set aws_access_key_id "${AWS_KEY}"
          - aws configure set aws_secret_access_key "${AWS_SECRET}"
          - eval $(aws ecr get-login --no-include-email --region eu-west-2 | sed 's;https://;;g')

          - docker build -t kidsloop-hub k8s/docker/service-hub/
          - docker tag kidsloop-hub:latest 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-base-images:nginx-hub-$BITBUCKET_BUILD_NUMBER
          - docker tag kidsloop-hub:latest 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-base-images:nginx-hub
          - docker push 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-base-images:nginx-hub-$BITBUCKET_BUILD_NUMBER
          - docker push 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-base-images:nginx-hub

        services:
          - docker
        caches:
          - pip
