repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  
  - name: jetstack
    url: https://charts.jetstack.io/

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  
  - name: fluent
    url: https://fluent.github.io/helm-charts

releases:

  - name: redis
    namespace: persistence
    chart: bitnami/redis
    version: ~11.3.4
    values:
      - cluster:
          slaveCount: 3
      - metrics:
          enabled: true
      - usePassword: false
      - slave:
          persistence:
            enabled: false
      - master:
          persistence:
            enabled: false
      - networkPolicy:
          enabled: true
          ingressNSMatchLabels:
            redis-namespace: "true"
          ingressNSPodMatchLabels:
            redis-client: "true"

  - name: nginx-ingress
    namespace: default
    chart: ingress-nginx/ingress-nginx
    version: ~3.8.0

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: ~1.0.4
    values:
      - installCRDs: true

  - name: prometheus
    namespace: monitoring
    chart: bitnami/kube-prometheus
    version: ~3.0.1
    values:
      - global:
          storageClass: premium-hdd
      - operator:
          createCustomResource: false
      - prometheus:
          persistence:
            enabled: true
            storageClass: premium-hdd
            size: 8Gi
      - alertmanager:
          enabled: false
      - kubeProxy:
          enabled: false

  - name: letsencrypt
    namespace: cert-manager
    chart: ./charts/live/letsencrypt

  - name: vietnam-ecr-token
    namespace: okc
    chart: ./charts/live/ecr-token
    version: ~0.1.0
    values:
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

  - name: vietnam-sfu
    namespace: okc
    chart: ./charts/live/sfu
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - hostNetworking: true
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  - name: vietnam-sfu-gateway
    namespace: okc
    chart: ./charts/live/sfu-gateway
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          hosts:
            - host: vn-bfc.dev.kidsloop.net
              paths:
                - "/sfu"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi


  - name: vietnam-static
    namespace: okc
    chart: ./charts/live/static
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          hosts:
            - host: vn-bfc.dev.kidsloop.net
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi

  - name: vietnam-hub
    namespace: okc
    chart: ./charts/live/hub
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          hosts:
            - host: vn-bfc.dev.kidsloop.net
              paths:
                - "/hub"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi

  - name: vietnam-live
    namespace: okc
    chart: ./charts/live/live
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          hosts:
            - host: vn-bfc.dev.kidsloop.net
              paths:
                - "/graphql"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  - name: vietnam-user-service
    namespace: okc
    chart: ./charts/live/user-service
    values:
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          hosts:
            - host: vn-bfc.dev.kidsloop.net
              paths:
                - "/user/graphql"

  - name: fluentbit
    namespace: monitoring
    chart: fluent/fluent-bit
    values:
      - extraVolumes:
          - name: aws-credentials
            secret:
              secretName: aws-credentials-fluentbit
      - extraVolumeMounts: 
          - name: aws-credentials
            mountPath: "/root/.aws"
            readOnly: true
      - config:
          outputs: >
            [OUTPUT]
                Name cloudwatch_logs
                Match *
                region ap-northeast-2
                log_group_name /bizflycloud/kubernetes
                log_stream_prefix vn

  - name: postgresql-ha
    namespace: persistence
    chart: bitnami/postgresql-ha
    values:
      - global:
          storageClass: premium-hdd
      - postgresql:
          existingSecret: postgresql
          username: kidsloop
          database: kidsloop
      - persistence:
          size: 8Gi
          storageClass: premium-hdd
      - pgpool:
          enabled: true
          replicaCount: 2
      - initdbScripts:
          db-init.sql: |
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
            CREATE EXTENSION IF NOT EXISTS "pgcrypto";
          