apiVersion: v1
kind: Service
metadata:
  name: {{ include "live-backend.fullname" . }}-svc
  labels:
    {{- include "live-backend.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "live-backend.selectorLabels" . | nindent 4 }}
  type: ClusterIP
