apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "live-backend.fullname" . }}
  labels:
    {{- include "live-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "live-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "live-backend.selectorLabels" . | nindent 8 }}
        redis-client: "true"
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
 
        env:
          - name: NODE_ENV
            value: "beta"
          - name: PORT
            value: "8080"
          - name: REDIS_HOST
            value: {{ .Values.redisHost }}
          - name: REDIS_PORT
            value: {{ .Values.redisPort | quote }}
          - name: ASSESSMENT_ENDPOINT
            value: {{ .Values.assessmentEndpoint }}
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-url

          - name: JWT_ISUER
            value: kidsloops-live
          - name: JWT_ALGORITHM
            valueFrom:
              secretKeyRef:
                name: live-backend-jwt
                key: ALGORITHM
          - name: JWT_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: live-backend-jwt
                key: PRIVATE_KEY
          - name: JWT_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: live-backend-jwt
                key: PUBLIC_KEY

      {{- if eq .Values.provider "gcp" }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.postgresql_instance }}=tcp:5432"
        securityContext:
          runAsNonRoot: true  
      {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq .Values.provider "gcp" }}
      serviceAccountName: cloudsql-proxy
      {{- end }}
