{{- if not (eq .Values.provider "gcp") }}

{{ $fullname := include "live-backend.fullname" .}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}-ingress
  labels:
    {{- include "live-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .endpoint.hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .endpoint.secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
        {{- range .paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullname }}-svc
            servicePort: http
        {{- end }}
  {{- end }}

{{- end}}