apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : {{ .Values.gcp.project }}
  name: "kidsloop"
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: kidsloop

