apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : {{ .Values.gcp.project }}
  name: kidsloop
spec:
  databaseVersion: MYSQL_5_7
  region: {{ .Values.gcp.region }}
  settings:
    availabilityType: "REGIONAL"
    tier: db-f1-micro
    diskAutoresize: true
    diskSize: 10
    diskType: PD_SSD
    backupConfiguration:
      binaryLogEnabled: true
      enabled: true
    ipConfiguration:
      requireSsl: true
      privateNetworkRef: 
        external: {{ .Values.gcp.network }}
        #requireSsl: true
        