apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : "{{ .Values.gcp.project }}"  
  name: "{{ .Values.gcp.mysql_name }}"
spec:
  databaseVersion: {{ .Values.gcp.mysql_version }}
  region: {{ .Values.gcp.region }}
  settings:
    availabilityType: "REGIONAL"
    tier: "{{ .Values.gcp.mysql_tier }}"
    diskAutoresize: true
    diskSize: {{ .Values.gcp.mysql_disk_size }}
    diskType: "{{ .Values.gcp.mysql_disk_type }}"
    backupConfiguration:
      binaryLogEnabled: true
      enabled: true
    ipConfiguration:
      requireSsl: false
      ipv4Enabled: false  # No public IP address
      privateNetworkRef: 
        external: "{{ .Values.gcp.network }}"
      requireSsl: true
    databaseFlags:
    # See here
    # https://calmisland.atlassian.net/wiki/spaces/SRE/pages/1997471773/CMS+Release
    - name: innodb_ft_max_token_size
      value: '84'
    - name: innodb_ft_min_token_size
      value: '1'
    - name: slow_query_log
      value: 'on'
    - name: long_query_time
      value: '1'
    - name: log_output
      value: 'FILE'
