apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : "{{ .Values.gcp.project }}"
  name: "{{ .Values.gcp.mysql_user}}"
spec:
  instanceRef:
    name: "{{ .Values.gcp.mysql_name }}"
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        key: "mysql-password"
        name: "mysql"