nameOverride: ""
fullnameOverride: ""
replicaCount: 1
imagePullSecrets: []


image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-user
  pullPolicy: Always
  tag: latest

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_method = OPTIONS) {
        more_set_headers "Access-Control-Allow-Origin: $allowed_origin";
        more_set_headers "Access-Control-Allow-Headers: Content-Type";
        return 200;
      }
      more_set_headers "Access-Control-Allow-Origin: $allowed_origin";
      more_set_headers "Access-Control-Allow-Credentials: true";
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]
  
resources: {}

