kube-prometheus-stack:
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  enabled: true
  prometheus:
    prometheusSpec:

      ## If true, a nil or {} value for prometheus.prometheusSpec.ruleSelector will cause the
      ## prometheus resource to be created with selectors based on values in the helm deployment,
      ## which will also match the PrometheusRule resources created
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  grafana:
    # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
    additionalDataSources:
      - name: Loki
        url: http://monitoring-loki.monitoring.svc.cluster.local:3100
        orgId: 1
        type: loki
    serviceMonitor:
      enabled: true
      interval: 1m
    persistence:
      type: pvc
      enabled: true
      # storageClassName: gp2
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      # annotations: {}
      finalizers:
        - kubernetes.io/pvc-protection
      # selectorLabels: {}
      # subPath: ""
      # existingClaim:

    grafana.ini:
      # Customise settings in the grafana.ini file
      # https://grafana.com/docs/grafana/latest/administration/configuration/
      # server:
      #   # The full public facing url you use in browser, used for redirects and emails
      #   root_url: 

    ingress:
      enabled: false
      # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
      # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
      # ingressClassName: nginx
      # Values can be templated
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      labels:
        app: grafana
      path: /
      # pathType is only for k8s >= 1.1=
      pathType: Prefix
      hosts:
        - grafana.devops.klpsre.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.devops.klpsre.com

loki-stack:
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  enabled: true
  loki:
    enabled: true
    # https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml
    serviceMonitor:
      enabled: true
      # interval: ""
      # additionalLabels: {}
      # annotations: {}

    serviceAccount:
      annotations: {} # TODO - add role
    # config:
    #   # https://grafana.com/docs/loki/latest/configuration/examples/
    #   schema_config:
    #     configs:
    #     - from: 2020-05-15
    #       store: aws
    #       object_store: s3
    #       schema: v11
    #       index:
    #         prefix: loki_index
    #         period: 0
    #   storage_config:
    #     aws:
    #       s3: s3://us-east-2/loki-test-bucket-dev-east-2
    #       dynamodb:
    #         dynamodb_url: dynamodb://us-east-2
    #   table_manager:
    #     retention_deletes_enabled: true
    #     retention_period: 336h

  promtail:
    enabled: true

  fluent-bit:
    enabled: false

  grafana:
    # not required - already included with kube-prometheus-stack
    enabled: false
    sidecar:
      datasources:
        enabled: true

  prometheus:
    # not required - already included with kube-prometheus-stack
    enabled: false
