liveJwtKey:
  # If set to true, a live JWT key is supplied (needed for live assessment, etc)
  enabled: false
  # Name of existing k8 secret
  existingSecretName: live-jwt-credentials
  passphrase:
    # If the JWT private key is encrypted with a passphrase, use these settings to supply it
    enabled: false
    literal: ""
    secretFieldRef: "jwt_private_passphrase"

replicaCount: 1

image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-live-backend
  pullPolicy: Always
  tag: master-latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

redisPort: 6379

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]
  
resources: {}

sqlProxy:
  resources:
      # The proxy's memory use scales linearly with the number of active
      # connections. Fewer open connections will use less memory. Adjust
      # this value based on your application's requirements.
      # The proxy's CPU use scales linearly with the amount of IO between
      # the database and the application. Adjust this value based on your
      # application's requirements.
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
      
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80