liveJwtKey:
  # If set to true, a live JWT key is supplied (needed for live assessment, etc)
  enabled: false
  # Name of existing k8 secret
  existingSecretName: live-jwt-credentials
  passphrase:
    # If the JWT private key is encrypted with a passphrase, use these settings to supply it
    enabled: false
    literal: ""
    secretFieldRef: "jwt_private_passphrase"

replicaCount: 1

image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-live-backend
  pullPolicy: Always
  tag: master-latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

redisPort: 6379

ingress:
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt"
  }
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]
  
resources: {}

