environments:
  vietnam:
    values:
      - ../../../env/vietnam/.env.yaml
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  oc:
    values:
      - ../../../env/oc/.env.yaml
          
repositories:

  - name: jetstack
    url: https://charts.jetstack.io/

releases:

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: ~1.0.4
    values:
      - installCRDs: true

  # - name: letsencrypt
  #   namespace: cert-manager
  #   chart: ../charts/letsencrypt

    

  
