environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-loadtest:
    values:
      - ../../../env/vietnam-loadtest/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml

repositories:

  - name: jetstack
    url: https://charts.jetstack.io/

releases:

  {{- if ne .Values.kl_domain ".kidsloop.vn" }}
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.7.2
    force: true
    values:
      - installCRDs: true

  - name: letsencrypt
    chart: ../charts/letsencrypt
    namespace: cert-manager
  {{- end }}  



