environments:
  vietnam-sre-dev:
    values:
      - ../../../env/vietnam-sre-dev/.env.yaml
  vietnam-vng-dev:
    values:
      - ../../../env/vietnam-vng-dev/.env.yaml      
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  
repositories:

  - name: jetstack
    url: https://charts.jetstack.io/

releases:

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: ~1.2.0
    condition: helm_cert_manager.enabled
    values:
      - installCRDs: true

  - name: letsencrypt
    namespace: cert-manager
    chart: ../charts/letsencrypt
    condition: helm_cert_manager.enabled