environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-loadtest:
    values:
      - ../../../env/vietnam-loadtest/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml

releases:
  {{- if eq .Values.provider "gcp" }}
  - name: h5p-service-external
    namespace: okc
    chart: ../charts/h5p-service-external
    values:
      - domain: {{ .Values.kl_domain }}
      # RK - use H5P in SG
      - externalServices:
          h5p:
            enabled: true
  {{- end}}