

environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml
      
releases:
  - name: hub
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/hub
    values:
      - provider: {{ .Values.provider }}
        serviceType: {{ .Values.k8s_service_type }}
        imagePullSecrets:
          - name: {{ .Values.hub_image_pull_secrets }}
        image:
          repository: {{ .Values.hub_image_repository }}
          tag: {{ .Values.hub_image_tag }}
        ingress:
          tls:
            - endpoint:
                hosts:
                  - hub{{ .Values.kl_domain }}      
                secretName: "letsencrypt-hub{{ .Values.kl_domain }}" 
          hosts:
            - host: hub{{ .Values.kl_domain }}
              paths:
                - "/"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        autoscaling:
          enabled: true
          minReplicas: {{ .Values.hub_min_replica_count }}
          maxReplicas: {{ .Values.hub_max_replica_count }}