environments:
  vietnam-sre-dev:
    values:
      - ../../../env/vietnam-sre-dev/.env.yaml
  vietnam-vng-dev:
    values:
      - ../../../env/vietnam-vng-dev/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml

repositories:

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:

  # INGRESSES
  # ---------------------------------------------------------------------------------------
  # Only deploy to Bizflycloud - for other clouds deploy using cloud-native ingress
  # This provides an ingress endpoint for inbound traffic

  - name: ingress-nginx
    namespace: default
    chart: ingress-nginx/ingress-nginx
    condition: helm_nginx_ingress.enabled
    version: 3.29.0
    values:
      - controller:
          config:
            ssl-redirect: "false"
            ssl-protocols: "SSLv3 TLSv1 TLSv1.1 TLSv1.2"
            use-forwarded-headers: "true"
            forwarded-for-header: "true"
            proxy-add-original-uri-header: "true"
            use-gzip: "true"
          service:
            annotations:
              nginx.ingress.kubernetes.io/configuration-snippet: |
                more_set_headers "Access-Control-Allow-Origin: $http_origin";
              nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
              nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
              nginx.ingress.kubernetes.io/enable-cors: "true"

  {{- if eq .Values.provider "gcp" }}
  
  - name: ingress
    namespace: okc
    chart: ../charts/mono-ingress-gcp
    values:
      - domain: {{ .Values.kl_domain }}

  - name: ingress-backend-config-hub
    namespace: okc
    chart:  ../charts/mono-ingress-backend-config-gcp
    values: 
      - name: hub
      - cdn:
          enabled: true
      - healthCheck:
          requestPath: /
          port: 80
  
  - name: ingress-backend-config-kl2-static
    namespace: okc
    chart:  ../charts/mono-ingress-backend-config-gcp
    values: 
      - name: kl2-static
      - cdn:
          enabled: true
      - healthCheck:
          requestPath: /
          port: 80
        
  - name: ingress-backend-config-kl2
    namespace: okc
    chart:  ../charts/mono-ingress-backend-config-gcp
    values: 
      - name: kl2
      - healthCheck:
          requestPath: /v1/ping
          port: 8088  

  - name: ingress-backend-config-static
    namespace: okc
    chart:  ../charts/mono-ingress-backend-config-gcp
    values: 
      - name: static
      - cdn:
          enabled: true
      - healthCheck:
          requestPath: /
          port: 80

  - name: ingress-backend-config-sfu-gateway
    namespace: okc
    chart:  ../charts/mono-ingress-backend-config-gcp
    values: 
      - name: sfu-gateway
      - healthCheck:
          requestPath: /server-health
          port: 8080

  - name: ingress-backend-config-live
    namespace: okc
    chart:  ../charts/mono-ingress-backend-config-gcp
    values: 
      - name: live
      - healthCheck:
          requestPath: /metrics
          port: 8080
  
  - name: ingress-backend-config-user
    namespace: okc
    chart:  ../charts/mono-ingress-backend-config-gcp
    values: 
      - name: user
      - healthCheck:
          requestPath: /.well-known/apollo/server-health
          port: 8080

  {{- end}}
