environments:
  vietnam:
    values:
      - ../../../env/vietnam/.env.yaml
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml

releases:

  # ECR TOKEN
  # ---------------------------------------------------------------------------------------
  # This provides an cron job which refreshes the AWS ECR token to allow download of docker 
  # images from the Kidsloop docker ECR.

  - name: vietnam-ecr-token
    namespace: okc
    chart: ../charts/ecr-token
    version: ~0.1.0
    values:
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi



  # HUB
  # ---------------------------------------------------------------------------------------
  # Only deploy to BizFlyCloud - on other clouds depoy to Storage bucket and CDN  
  
  - name: vietnam-hub
    namespace: okc
    chart: ../charts/hub
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - hub{{ .Values.kl_domain }}      
                secretName: "letsencrypt-hub{{ .Values.kl_domain }}" 
          hosts:
            - host: hub{{ .Values.kl_domain }}
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi



  # KL2
  # ---------------------------------------------------------------------------------------
  
  - name: vietnam-kl2
    namespace: okc
    chart: ../charts/kl2
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      {{- if eq .Values.provider "gcp" }}
      - project: {{ .Environment.Values.terraform_project }}
      - region: {{ .Environment.Values.terraform_region }}
      - db_instance: {{ .Environment.Values.gcp.mysql.name }}
      - mysql_proxy_ip:  {{ .Environment.Values.mysql_proxy_ip}}
      {{- end}}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - kl2{{ .Values.kl_domain }}
                secretName: "letsencrypt-kl2{{ .Values.kl_domain }}"
          hosts:
            - host: kl2{{ .Values.kl_domain }}
              paths:
                - "/v1"
      
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

      - configuration:
          db_hostname: {{ .Values.mysql_host }}
          db_name: {{ .Values.mysql_database }}
          db_username: {{ .Values.mysql_username }}
          redis_host: {{ .Values.redis_host }}
          ams_endpoint: https://api{{ .Values.kl_domain }}/user
          cors_domain_list: https://*{{ .Values.kl_domain }}
          {{ if .Values.storage }}
          storage_endpoint: {{ .Values.storage.endpoint }}
          storage_region: {{ .Values.storage.region }}
          storage_bucket: {{ .Values.storage.bucket }}
          storage_protocol: {{ .Values.storage.protocol }}
          storage_download_mode: {{ .Values.storage.download_mode }}
          {{ end }}
          # This should be removed with new image
          ams_assessment_jwt_public_key_path: ./jwt_public_key.pem
          


  # KL2 STATIC
  # ---------------------------------------------------------------------------------------
  
  - name: vietnam-kl2-static
    namespace: okc
    chart: ../charts/kl2-static
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - kl2{{ .Values.kl_domain }}
                secretName: "letsencrypt-kl2{{ .Values.kl_domain }}"
          hosts:
            - host: kl2{{ .Values.kl_domain }}
              paths:
                - "/"
      - image:
          tag: {{ .Values | get "image_versions.kl2_static" .Environment.Name }}
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
 
 
 
  # LIVE
  # ---------------------------------------------------------------------------------------

  - name: vietnam-live
    namespace: okc
    chart: ../charts/live
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      - prometheus_enabled: {{ .Values.helm_prometheus.enabled }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.kl_domain }}
                secretName: "letsencrypt-live{{ .Values.kl_domain }}"
          hosts:
            - host: live{{ .Values.kl_domain }}
              paths:
                - "/graphql"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - redisHost: {{ .Values.redis_host }}



  # SFU
  # ---------------------------------------------------------------------------------------

  - name: vietnam-sfu
    namespace: okc
    chart: ../charts/sfu
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - hostNetworking: true
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - sfuManagerConfiguration:
          promHost: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      - redisHost: {{ .Values.redis_host }}



  # SFU-GATEWAY
  # ---------------------------------------------------------------------------------------

  - name: vietnam-sfu-gateway
    namespace: okc
    chart: ../charts/sfu-gateway
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.kl_domain }}
                secretName: "letsencrypt-live{{ .Values.kl_domain }}"
          hosts:
            - host: live{{ .Values.kl_domain }}
              paths:
                - "/sfu"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - redisHost: {{ .Values.redis_host }}


      
  # STATIC
  # ---------------------------------------------------------------------------------------

  - name: vietnam-static
    namespace: okc
    chart: ../charts/static
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.kl_domain }}
                secretName: "letsencrypt-live{{ .Values.kl_domain }}"
          hosts:
            - host: live{{ .Values.kl_domain }}
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi


   
  # USER SERVICE
  # ---------------------------------------------------------------------------------------
  
  - name: vietnam-user-service
    namespace: okc
    chart: ../charts/user-service
    values:
      - provider: {{ .Values.provider }}
      - serviceType: {{ .Values.k8s_service_type }}
      - image:
          repository: 494634321140.dkr.ecr.ap-northeast-2.amazonaws.com/vietnam-user-service
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - api{{ .Values.kl_domain }}
                secretName: "letsencrypt-api{{ .Values.kl_domain }}"
          hosts:
            - host: api{{ .Values.kl_domain }}
              paths:
                - "/user"
      - postgresql_host: {{ .Values.postgresql_host }}
      - postgresql_username: {{ .Values.postgresql_username }}
      - postgresql_database: {{ .Values.postgresql_database}}
      {{- if eq .Values.provider "gcp" }}
      - postgresql_instance: {{ .Environment.Values.gcp.postgresql.name }}
      - project: {{ .Environment.Values.terraform_project }}
      - region: {{ .Environment.Values.terraform_region }}
      {{- end}}
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
