environments:
  vietnam:
    values:
      - ../../../env/vietnam/.env.yaml
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  oc:
    values:
      - ../../../env/oc/.env.yaml

releases:

  # ECR TOKEN
  # ---------------------------------------------------------------------------------------
  # This provides an cron job which refreshes the AWS ECR token to allow download of docker 
  # images from the Kidsloop docker ECR.

  - name: vietnam-ecr-token
    namespace: okc
    chart: ../charts/ecr-token
    version: ~0.1.0
    values:
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi



  # HUB
  # ---------------------------------------------------------------------------------------
  # Only deploy to BizFlyCloud - on other clouds depoy to Storage bucket and CDN  
  
  - name: vietnam-hub
    namespace: okc
    chart: ../charts/hub
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - hub{{ .Environment.Values.kl_domain }}      
                secretName: "letsencrypt-hub{{ .Environment.Values.kl_domain }}" 
          hosts:
            - host: hub{{ .Environment.Values.kl_domain }}
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi



  # KL2
  # ---------------------------------------------------------------------------------------
  
  - name: vietnam-kl2
    namespace: okc
    chart: ../charts/kl2
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - kl2{{ .Environment.Values.kl_domain }}
                secretName: "letsencrypt-kl2{{ .Environment.Values.kl_domain }}"
          hosts:
            - host: kl2{{ .Environment.Values.kl_domain }}
              paths:
                - "/v1"
      - configuration:
          db_hostname: {{ .Environment.Values.mysql_host }}
          db_name: {{ .Environment.Values.mysql_database }}
          db_username: {{ .Environment.Values.mysql_username }}
          redis_host: {{ .Environment.Values.redis_host }}



  # KL2 STATIC
  # ---------------------------------------------------------------------------------------
  
  - name: vietnam-kl2-static
    namespace: okc
    chart: ../charts/kl2-static
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - kl2{{ .Environment.Values.kl_domain }}
                secretName: "letsencrypt-kl2{{ .Environment.Values.kl_domain }}"
          hosts:
            - host: kl2{{ .Environment.Values.kl_domain }}
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
 
 
 
  # LIVE
  # ---------------------------------------------------------------------------------------

  - name: vietnam-live
    namespace: okc
    chart: ../charts/live
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - prometheus_enabled: {{ .Environment.Values.helm_prometheus.enabled }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
          tls:
            - endpoint:
                hosts:
                  - live{{ .Environment.Values.kl_domain }}
                secretName: "letsencrypt-live{{ .Environment.Values.kl_domain }}"
          hosts:
            - host: live{{ .Environment.Values.kl_domain }}
              paths:
                - "/graphql"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - redisHost: {{ .Environment.Values.redis_host }}



  # SFU
  # ---------------------------------------------------------------------------------------

  - name: vietnam-sfu
    namespace: okc
    chart: ../charts/sfu
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - hostNetworking: true
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - sfuManagerConfiguration:
          promHost: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      - redisHost: {{ .Environment.Values.redis_host }}



  # SFU-GATEWAY
  # ---------------------------------------------------------------------------------------

  - name: vietnam-sfu-gateway
    namespace: okc
    chart: ../charts/sfu-gateway
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - live{{ .Environment.Values.kl_domain }}
                secretName: "letsencrypt-live{{ .Environment.Values.kl_domain }}"
          hosts:
            - host: live{{ .Environment.Values.kl_domain }}
              paths:
                - "/sfu"
      - resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - redisHost: {{ .Environment.Values.redis_host }}


      
  # STATIC
  # ---------------------------------------------------------------------------------------

  - name: vietnam-static
    namespace: okc
    chart: ../charts/static
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
          tls:
            - endpoint:
                hosts:
                  - live{{ .Environment.Values.kl_domain }}
                secretName: "letsencrypt-live{{ .Environment.Values.kl_domain }}"
          hosts:
            - host: live{{ .Environment.Values.kl_domain }}
              paths:
                - "/"
      - resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi


   
  # USER SERVICE
  # ---------------------------------------------------------------------------------------
  
  - name: vietnam-user-service
    namespace: okc
    chart: ../charts/user-service
    values:
      - provider: {{ .Environment.Values.provider }}
      - serviceType: {{ .Environment.Values.k8s_service_type }}
      - image:
          repository: 494634321140.dkr.ecr.ap-northeast-2.amazonaws.com/vietnam-user-service
      - imagePullSecrets:
          - name: ecr-registry
      - ingress:
          tls:
            - endpoint:
                hosts:
                  - api{{ .Environment.Values.kl_domain }}
                secretName: "letsencrypt-api{{ .Environment.Values.kl_domain }}"
          hosts:
            - host: api{{ .Environment.Values.kl_domain }}
              paths:
                - "/user"
      - postgresql_host: {{ .Environment.Values.postgresql_host }}


      
  

  