environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-loadtest:
    values:
      - ../../../env/vietnam-loadtest/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml
      
releases:

  # ECR TOKEN - VIETNAM
  # ---------------------------------------------------------------------------------------
  # This provides an cron job which refreshes the AWS ECR token to allow download of docker 
  # images from the Kidsloop docker ECR.
 
  - name: ecr-token-vn
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/ecr-token
    version: ~0.1.0
    condition: helm_ecr_token_vietnam.enabled
    values:
      - suffix: "-vn"
      - secret_name: "ecr-registry-vn"
      - credential_secret_name: "ecr-credentials-vn-pull"
      - aws_region: "ap-southeast-1"
      - aws_account_id: "242787759841"
      - image: {{ .Values.ecr_token_infra_repository }}
      - image_pull_secret: "ecr-registry-infra"
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

  - name: ecr-token-infra-singapore
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/ecr-token
    version: ~0.1.0
    condition: helm_ecr_token_vietnam.enabled
    values:
      - suffix: "-infra-singapore"
      - secret_name: "ecr-registry-infra-singapore"
      - credential_secret_name: "ecr-credentials-infra-pull"
      - aws_region: "ap-southeast-1"
      - aws_account_id: "942095822719"
      - image: {{ .Values.ecr_token_infra_repository }}
      - image_pull_secret: "ecr-registry-infra"
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
  # ECR TOKEN
  # ---------------------------------------------------------------------------------------
  # This provides an cron job which refreshes the AWS ECR token to allow download of docker
  # images from the Kidsloop docker ECR.

  - name: ecr-token-infra
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/ecr-token
    version: ~0.1.0
    condition: helm_ecr_token_infra.enabled
    values:
      - suffix: "-infra"
      - secret_name: "ecr-registry-infra"
      - credential_secret_name: "ecr-credentials-infra-pull"       
      - aws_region: "eu-west-2"
      - aws_account_id: "942095822719"
      - image: {{ .Values.ecr_token_infra_repository }}
      - image_pull_secret: "ecr-registry-infra"
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi           

  - name: mysql-backup
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/mysql-backup
    version: ~0.1.0
    condition: helm_db_backup.enabled
    values:
      - image: {{ .Values.mysql_backup_repository }}
      - mysql_host: {{ .Values.mysql_host }}
      - mysql_username: {{ .Values.mysql_username }}
      - mysql_database: {{ .Values.mysql_database }}
      - storage_endpoint: {{ .Values.helm_db_backup.endpoint }}
      - storage_region: {{ .Values.helm_db_backup.region }}
      - storage_bucket: {{ .Values.helm_db_backup.bucket }}
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi    

  - name: postgresql-backup
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/postgresql-backup
    version: ~0.1.0
    condition: helm_db_backup.enabled
    values:
      - image: {{ .Values.postgresql_backup_repository }}
      - postgresql_host: {{ .Values.postgresql_host }}
      - postgresql_username: {{ .Values.postgresql_username }}
      - postgresql_database: {{ .Values.postgresql_database }}
      - storage_endpoint: {{ .Values.helm_db_backup.endpoint }}
      - storage_region: {{ .Values.helm_db_backup.region }}
      - storage_bucket: {{ .Values.helm_db_backup.bucket }}
      - resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
