environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-loadtest:
    values:
      - ../../../env/vietnam-loadtest/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
      
releases:
  - name: live-frontend
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/live-frontend
    values:
      - provider: {{ .Values.provider }}
        serviceType: {{ .Values.k8s_service_type }}
        image:
          repository: {{ .Values.live_frontend_image_repository }} 
          tag: {{ .Values.live_frontend_image_tag }}
        imagePullSecrets:
          - name: {{ .Values.live_frontend_image_pull_secrets }}
        appVersion: {{ .Values.live_frontend_appVersion }}
        ingress:
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt"
            kubernetes.io/ingress.class: "nginx"
            ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/websocket-services: "live-frontend-svc"
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/send-timeout: "3600"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          {{- if eq .Values.provider "vngcloud" }}
            nginx.ingress.kubernetes.io/client-body-buffer-size: 8M
            nginx.ingress.kubernetes.io/proxy-body-size: 128m
            nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
            nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
            nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 128m
            nginx.ingress.kubernetes.io/server-snippet: |
              http2_max_header_size 1024k;
              http2_max_field_size 1024k;  
          {{- end }}
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.kl_domain }}
                secretName: {{- if eq .Values.kl_domain ".kidsloop.vn" }} "wildcard-kidsloop-vn" {{- else }} "letsencrypt-live{{ .Values.kl_domain }}" {{- end }}
          hosts:
            - host: live{{ .Values.kl_domain }}
              paths:
                - "/"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        autoscaling:
          enabled: true
          minReplicas: {{ .Values.live_frontend_min_replica_count }}
          maxReplicas: {{ .Values.live_frontend_max_replica_count }}