environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml
      
releases:
  - name: live-frontend
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/live-frontend
    values:
      - provider: {{ .Values.provider }}
        serviceType: {{ .Values.k8s_service_type }}
        image:
          repository: {{ .Values.live_frontend_image_repository }} 
          tag: {{ .Values.live_frontend_image_tag }}
        imagePullSecrets:
          - name: {{ .Values.live_frontend_image_pull_secrets }}
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.kl_domain }}
                secretName: "letsencrypt-live{{ .Values.kl_domain }}"
          hosts:
            - host: live{{ .Values.kl_domain }}
              paths:
                - "/"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi
        autoscaling:
          enabled: true
          minReplicas: {{ .Values.live_frontend_min_replica_count }}
          maxReplicas: {{ .Values.live_frontend_max_replica_count }}