environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml
      
repositories:
- name: "mongodb"
  url: "https://mongodb.github.io/helm-charts"

releases:

{{- if eq .Values.provider "gcp-do-not-deploy-yet" }}

# atlas operator and crds
- name: mongodb-atlas-operator
  namespace: {{ .Values.k8s_namespace_kidsloop }}
  # labels:
    # component: "h5p"
  chart: mongodb/mongodb-atlas-operator
  version: 0.2.1
  installed: true
  
- name: mongodb-atlas-cluster
  namespace: {{ .Values.k8s_namespace_kidsloop }}
  labels:
    component: "h5p"
  chart: ../charts/atlas-cluster
  version: 0.1.5
  installed: true
  values:
    - project:
        name: kidsloop
        atlasProjectName: kidsloop
        projectIpAccessList:
          - ipAddress: "0.0.0.0/0"
            comment: "All IP addresses"

      mongodb:
        providerSettings:
          instanceSizeName: M0
          providerName: GCP
          backingProviderName: GCP
          regionName: ASIA_SOUTH_1
        
      users:
        - username: {{ .Values.mongodb.username }}
          databaseName: {{ .Values.mongodb.database }}
          roles:
            - databaseName: {{ .Values.mongodb.database }}
              roleName: atlasAdmin
{{- end }}
