environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-loadtest:
    values:
      - ../../../env/vietnam-loadtest/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml

releases:
  {{- if eq .Values.provider "vngcloud" }} 
  - name: nightwatch
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/nightwatch
    values:
      - image:
          repository: "{{ .Values.nightwatch_image_repository }}"
          tag: "{{ .Values.nightwatch_image_tag }}"
        imagePullSecrets:
          - name: {{ .Values.nightwatch_image_pull_secrets }}
        appVersion: {{ .Values.nightwatch_appVersion }}  
        room_id: "123"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
  {{- end }}