repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: fluent
    url: https://fluent.github.io/helm-charts

  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

  - name: grafana
    url: https://grafana.github.io/helm-charts

environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml
      
releases:

{{- if ne .Values.provider "gcp" }}

  - name: prometheus
    namespace: monitoring
    chart: bitnami/kube-prometheus
    version: ~3.0.1
    condition: helm_prometheus.enabled
    values:
      - global:
          storageClass: {{ .Values.persistentvolumeclaim_storage_class }}
      - operator:
          createCustomResource: false
      - prometheus:
          persistence:
            enabled: true
            storageClass: {{ .Values.persistentvolumeclaim_storage_class }}
            size: 8Gi
      - alertmanager:
          enabled: false
      - kubeProxy:
          enabled: false

  - name: fluentbit
    namespace: monitoring
    chart: fluent/fluent-bit
    condition: helm_fluentbit.enabled
    values:
      - extraVolumes:
          - name: aws-credentials
            secret:
              secretName: aws-credentials-fluentbit
      - extraVolumeMounts: 
          - name: aws-credentials
            mountPath: "/root/.aws"
            readOnly: true
      - config:
          outputs: >
            [OUTPUT]
                Name cloudwatch_logs
                Match *
                region ap-southeast-1
                log_group_name {{ .Values.fluentbit_cloudwatch_log_stream }}
                log_stream_prefix k8s-
{{- end }}

  - name: monitoring
    namespace: monitoring
    chart: ../charts/kube-monitoring
    version: ~0.1.0
    condition: helm_kube_monitoring.enabled
    values:
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
      - kube-prometheus-stack:
          alertmanager:
            config:
              global:
                # This is the webhook URL to our own kidsloop slack app
                slack_api_url: 'https://hooks.slack.com/services/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'
            alertmanagerSpec:
              routePrefix: /alertmanager/
              externalUrl: https://mon{{ .Values.kl_domain }}/alertmanager/
            templateFiles:
              # This file is a simple template to pass helm variables through to the alertmanager instance
              kidsloop.helm.tmpl: |-
                {{`{{ define "slack.kidsloop.channel" }}`}}{{ .Values.kube_monitoring.slack_channel }}{{`{{ end }}`}}
                {{`{{ define "__credential_url" }}`}}{{ .Values.kube_monitoring.credential_url }}{{`{{ end }}`}}

            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt"
                # https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
                # type of authentication
                # nginx.ingress.kubernetes.io/auth-type: basic
                # # name of the secret that contains the user/password definitions
                # nginx.ingress.kubernetes.io/auth-secret: basic-auth
                # # message to display with an appropriate context why the authentication is required
                # nginx.ingress.kubernetes.io/auth-realm: 'mon{{ .Values.kl_domain }}'
                # These are the OAuth params
                nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
                nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
                # Other stuff for GKE LB
                kubernetes.io/ingress.allow-http: 'false'
                kubernetes.io/ingress.class: nginx
                kubernetes.io/ingress.global-static-ip-name: ingress-https-load-balancer
                # nginx.ingress.kubernetes.io/auth-url: "https://iss{{ .Values.kl_domain }}/auth"
                # nginx.ingress.kubernetes.io/auth-signin: "https://iss{{ .Values.kl_domain }}/auth?rd=$escaped_request_uri"
              labels: {}
              hosts:
                - mon{{ .Values.kl_domain }}
              paths:
                - /alertmanager/
              tls:
                - hosts:
                    - mon{{ .Values.kl_domain }}
                  secretName: mon-cert
          prometheus:
            prometheusSpec:
              externalUrl: https://mon{{ .Values.kl_domain }}/
              # externalUrl: https://mon{{ .Values.kl_domain }}/
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: standard
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt"
                # https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
                # type of authentication
                # nginx.ingress.kubernetes.io/auth-type: basic
                # # name of the secret that contains the user/password definitions
                # nginx.ingress.kubernetes.io/auth-secret: basic-auth
                # # message to display with an appropriate context why the authentication is required
                # nginx.ingress.kubernetes.io/auth-realm: 'mon{{ .Values.kl_domain }}'
                # These are the OAuth params
                nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
                nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
                # Other stuff for GKE LB
                kubernetes.io/ingress.allow-http: 'false'
                kubernetes.io/ingress.class: nginx
                kubernetes.io/ingress.global-static-ip-name: ingress-https-load-balancer
              labels: {}
              hosts:
                - mon{{ .Values.kl_domain }}
              paths:
                - /
              tls:
                - hosts:
                    - mon{{ .Values.kl_domain }}
                  secretName: mon-cert
          grafana:
            # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
            ingress:
              enabled: true
              # ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt"
                # https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
                # type of authentication
                # nginx.ingress.kubernetes.io/auth-type: basic
                # # name of the secret that contains the user/password definitions
                # nginx.ingress.kubernetes.io/auth-secret: basic-auth
                # # message to display with an appropriate context why the authentication is required
                # nginx.ingress.kubernetes.io/auth-realm: 'mon{{ .Values.kl_domain }}'
                # These are the OAuth params
                nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
                nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
                # Other stuff for GKE LB
                kubernetes.io/ingress.allow-http: 'false'
                kubernetes.io/ingress.class: nginx
                kubernetes.io/ingress.global-static-ip-name: ingress-https-load-balancer
              labels: {}
              hosts:
                - mon{{ .Values.kl_domain }}
              path: /grafana/
              pathType: ImplementationSpecific
              paths:
                - /grafana/
              tls:
                - hosts:
                    - mon{{ .Values.kl_domain }}
                  secretName: mon-cert
            grafana.ini:
              server:
                domain: mon{{ .Values.kl_domain }}
                root_url: "%(protocol)s://%(domain)s/grafana"
                serve_from_sub_path: true
        oauth2-proxy:
          enabled: true
          domain: mon{{ .Values.kl_domain }}
