repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: fluent
    url: https://fluent.github.io/helm-charts

  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

  - name: grafana
    url: https://grafana.github.io/helm-charts

environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml
      
releases:

{{- if ne .Values.provider "gcp" }}

  - name: prometheus
    namespace: monitoring
    chart: bitnami/kube-prometheus
    version: ~3.0.1
    condition: helm_prometheus.enabled
    values:
      - global:
          storageClass: {{ .Values.persistentvolumeclaim_storage_class }}
      - operator:
          createCustomResource: false
      - prometheus:
          persistence:
            enabled: true
            storageClass: {{ .Values.persistentvolumeclaim_storage_class }}
            size: 8Gi
      - alertmanager:
          enabled: false
      - kubeProxy:
          enabled: false

  - name: fluentbit
    namespace: monitoring
    chart: fluent/fluent-bit
    condition: helm_fluentbit.enabled
    values:
      - extraVolumes:
          - name: aws-credentials
            secret:
              secretName: aws-credentials-fluentbit
      - extraVolumeMounts: 
          - name: aws-credentials
            mountPath: "/root/.aws"
            readOnly: true
      - config:
          outputs: >
            [OUTPUT]
                Name cloudwatch_logs
                Match *
                region ap-southeast-1
                log_group_name {{ .Values.fluentbit_cloudwatch_log_stream }}
                log_stream_prefix k8s-
{{- end }}

  - name: monitoring
    namespace: monitoring
    chart: ../charts/kube-monitoring
    version: ~0.1.0
    condition: helm_kube_monitoring.enabled
    values:
      - kube-prometheus-stack:
          alertmanager:
            config:
              global:
                resolve_timeout: 5m
                # This is the webhook URL to our own kidsloop slack app
                slack_api_url: 'https://hooks.slack.com/services/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'

              route:
                group_by: ['job']
                group_wait: 30s
                group_interval: 5m
                repeat_interval: 12h
                receiver: 'slack-notifications'
                routes:
                - match:
                    alertname: Watchdog
                  receiver: 'null'
              receivers:
                - name: 'null'
                - name: 'slack-notifications'
                  slack_configs:
                    - channel: '#production-alerts'
                      send_resolved: true
                      icon_url: https://avatars3.githubusercontent.com/u/3380462
              templates:
                - '/etc/alertmanager/config/*.tmpl'

      # - global:
      #     storageClass: { { .Values.persistentvolumeclaim_storage_class }}
