repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: fluent
    url: https://fluent.github.io/helm-charts

environments:
  default:
    values:
      - ../../../env/vietnam/.env.yaml
  indonesia:
    values:
      - ../../../env/indonesia/.env.yaml
  oc:
    values:
      - ../../../env/oc/.env.yaml
      
releases:

  - name: prometheus
    namespace: monitoring
    chart: bitnami/kube-prometheus
    version: ~3.0.1
    condition: helm_prometheus.enabled
    values:
      - global:
          storageClass: premium-hdd
      - operator:
          createCustomResource: false
      - prometheus:
          persistence:
            enabled: true
            storageClass: premium-hdd
            size: 8Gi
      - alertmanager:
          enabled: false
      - kubeProxy:
          enabled: false

  - name: fluentbit
    namespace: monitoring
    chart: fluent/fluent-bit
    condition: helm_fluentbit.enabled
    values:
      - extraVolumes:
          - name: aws-credentials
            secret:
              secretName: aws-credentials-fluentbit
      - extraVolumeMounts: 
          - name: aws-credentials
            mountPath: "/root/.aws"
            readOnly: true
      - config:
          outputs: >
            [OUTPUT]
                Name cloudwatch_logs
                Match *
                region ap-northeast-2
                log_group_name /bizflycloud/kubernetes
                log_stream_prefix vn


