environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml

releases:
  {{- if eq .Values.provider "vngcdloud" }}
  
  - name: onboarding-scheduling
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/onboarding-scheduling
    values:
      - provider: {{ .Values.provider }}
        deployment_name: {{ .Values.deployment_name }}
        deployment_region: {{ .Values.deployment_region }}
        deployment_env: {{ .Values.env }}
        serviceType: {{ .Values.k8s_service_type }}
        image:
          repository: "{{ .Values.onboarding_scheduling_image_repository }}"
          tag: "{{ .Values.onboarding_scheduling_image_tag }}"
        imagePullSecrets:
          - name: {{ .Values.onboarding_scheduling_image_pull_secrets }}
        appVersion: {{ .Values.onboarding_scheduling_appVersion }}
        ingress:
          {{- if eq .Values.provider "gcp" }}
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt"
            kubernetes.io/ingress.class: "nginx"
            ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/send-timeout: "3600"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          {{- else }}
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt"
            nginx.ingress.kubernetes.io/configuration-snippet: |
              if ($request_method = OPTIONS) {
                more_set_headers "Access-Control-Allow-Origin: $allowed_origin";
                more_set_headers "Access-Control-Allow-Headers: Content-Type";
                return 200;
              }
              more_set_headers "Access-Control-Allow-Origin: $allowed_origin";
              more_set_headers "Access-Control-Allow-Credentials: true";          
          {{- end }}
          tls:
            - endpoint:
                hosts:
                  - onboarding-scheduling{{ .Values.kl_domain }}
                secretName: {{- if eq .Values.kl_domain ".kidsloop.vn" }} "wildcard-kidsloop-vn" {{- else }} "letsencrypt-onboarding-scheduling{{ .Values.kl_domain }}" {{- end }}
          hosts:
            - host: onboarding-scheduling{{ .Values.kl_domain }}
              paths:
                - "/"
        domain: {{ .Values.domain }}
        user_service_endpoint: https://api{{ .Values.kl_domain }}/user/graphql
        cms_backend_endpoint: https://cms{{ .Values.kl_domain }}/v1
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        autoscaling:
          enabled: true
          minReplicas: {{ .Values.onboarding_scheduling_min_replica_count }}
          maxReplicas: {{ .Values.onboarding_scheduling_max_replica_count }}

  {{- end }}