environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml
      
releases:
  - name: sfu
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/sfu
    values:
      - replicaCount: {{ .Values.sfu_manager_replica_count }}
        sfuManagerImage:
          repository: {{ .Values.sfu_manager_image_repository }}
          tag: {{ .Values.sfu_manager_image_tag }}
          imagePullSecrets:
            - name: {{ .Values.sfu_manager_image_pull_secrets }}
        sfuImage:
          repository: {{ .Values.sfu_image_repository }}
          tag: {{ .Values.sfu_image_tag | default "latest" }}
          imagePullSecrets:
            - name: {{ .Values.sfu_image_pull_secrets }}
        provider: {{ .Values.provider }}
        serviceType: {{ .Values.k8s_service_type }}
      # Important - use host networking in GCP, and use pod IP as hostname
        hostNetworking: true  # SFU addressable over internet
        usePodIpAsHostnameOverride: true  # Dump pod IP into HOSTNAME_OVERRIDE
        useIp: false  # Don't allow the SFU service to pick it's own IP address from the list of interfaces
        resources:
          requests:
            cpu: {{ .Values.sfu_pods_cpu_request }}
            memory: {{ .Values.sfu_pods_memory_request }}
          limits:
            cpu: {{ .Values.sfu_pods_cpu_limit }}
            memory: {{ .Values.sfu_pods_memory_limit }}
        sfuManagerResources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi            
        sfuManagerConfiguration:
          promHost: {{ .Values.prometheus_host }}
          desiredPodsGetter: {{ .Values.desired_pods_getter }}
          redisHost: {{ .Values.redis_host }}:6379
          pods: {{ .Values.sfu_pods_count }}
          promDesiredAvailable: {{ .Values.sfu_pods_count }}
        redisHost: {{ .Values.redis_host }}

