environments:
  vietnam-alpha:
    values:
      - ../../../env/vietnam-alpha/.env.yaml
  vietnam-beta:
    values:
      - ../../../env/vietnam-beta/.env.yaml
  vietnam-production:
    values:
      - ../../../env/vietnam-production/.env.yaml      
  indonesia-staging:
    values:
      - ../../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../../env/indonesia-rk-beta/.env.yaml
      
releases:
  - name: sfu-gateway
    namespace: {{ .Values.k8s_namespace_kidsloop }}
    chart: ../charts/sfu-gateway
    values:
      - provider: {{ .Values.provider }}
        serviceType: {{ .Values.k8s_service_type }}
        image:
          repository: {{ .Values.sfu_gateway_image_repository }}
          tag: {{ .Values.sfu_gateway_image_tag }}
        imagePullSecrets:
          - name: {{ .Values.sfu_gateway_image_pull_secrets }}
        appVersion: {{ .Values.sfu_gateway_appVersion }}
        ingress:
          {{- if eq .Values.provider "gcp" }}
          annotations: 
            cert-manager.io/cluster-issuer: "letsencrypt"
            kubernetes.io/ingress.class: "nginx"
            ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/websocket-services: "sfu-gateway-svc"
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/send-timeout: "3600"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          {{- end }}
          tls:
            - endpoint:
                hosts:
                  - live{{ .Values.kl_domain }}
                secretName: {{- if eq .Values.kl_domain ".kidsloop.vn" }} "wildcard-kidsloop-vn" {{- else }} "letsencrypt-live{{ .Values.kl_domain }}" {{- end }}
          hosts:
            - host: live{{ .Values.kl_domain }}
              paths:
                - "/sfu"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        redisHost: {{ .Values.redis_host }}
        autoscaling:
          enabled: true
          minReplicas: {{ .Values.sfu_gateway_min_replica_count }}
          maxReplicas: {{ .Values.sfu_gateway_max_replica_count }}