{{- if not (eq .Values.provider "gcp")  }}
{{- if not (eq .Values.provider "aws")  }}

{{ $fullname := include "hub.fullname" .}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}-ingress
  labels:
    {{- include "hub.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.host | quote }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ $fullname }}-svc
            servicePort: 80

{{- end }}
{{- end }}