{{- if not (eq .Values.provider "gcp")  }}
{{- if not (eq .Values.provider "aws")  }}

{{ $fullname := include "live-frontend.fullname" .}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}-ingress
  labels:
    {{- include "live-frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
        {{- range .paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullname }}-svc
            servicePort: 80
        {{- end }}
  {{- end }}

{{- end}}
{{- end}}