apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeURLMap
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : {{ .Values.gcp.project }}
  name: {{ .Values.bucket_id }}
spec:
  location: global
  defaultService:
    backendBucketRef:
      name: {{ .Values.bucket_id }}