apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : {{ .Values.gcp.project }}
  name: {{ .Values.bucket_id }}
spec:
  #cors
  #logging
  location: {{ .Values.gcp.region }}
  storageClass: REGIONAL
  uniformBucketLevelAccess: true
