apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: "{{ include "whitelabel-bucket.name" . }}-{{ .Values.project }}"
  labels:
    {{- include "whitelabel-bucket.labels" . | nindent 4 }}
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
    cnrm.cloud.google.com/project-id : "{{ .Values.project }}"
spec:
  location: {{ .Values.region }}
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  labels:
    {{- include "whitelabel-bucket.labels" . | nindent 4 }}
  name: "{{ include "whitelabel-bucket.name" . }}-accesscontrol"
  annotations:
    cnrm.cloud.google.com/project-id : "{{ .Values.project }}"
spec:
  bucketRef:
    name: "{{ include "whitelabel-bucket.name" . }}-{{ .Values.project }}"
  entity: allUsers
  role: READER