apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  labels:
    {{- include "whitelabel-bucket.labels" . | nindent 4 }}
  name: {{ include "whitelabel-bucket.name" . }}
  annotations:
    cnrm.cloud.google.com/project-id : "{{ .Values.project }}"
spec:
  displayName: "Service Account for {{ include "whitelabel-bucket.name" . }}"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  labels:
    {{- include "whitelabel-bucket.labels" . | nindent 4 }}
  name: {{ include "whitelabel-bucket.name" . }}
  annotations:
    cnrm.cloud.google.com/project-id : "{{ .Values.project }}"
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: "{{ include "whitelabel-bucket.name" . }}-{{ .Values.project }}"
  bindings:
    - role: roles/storage.admin
      members:
        - "serviceAccount:{{ include "whitelabel-bucket.name" . }}@{{ .Values.project }}.iam.gserviceaccount.com"