apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : "{{ .Values.gcp.project }}"  
  name: "{{ .Values.gcp.postgresql_name }}"
spec:
  databaseVersion: "{{ .Values.gcp.postgresql_version }}"
  region: "{{ .Values.gcp.region }}"
  settings:
    availabilityType: "REGIONAL"
    tier: "{{ .Values.gcp.postgresql_tier }}"
    diskAutoresize: true
    diskSize: {{ .Values.gcp.postgresql_disk_size }}
    diskType: "{{ .Values.gcp.postgresql_disk_type }}"
    backupConfiguration:
      enabled: true
      pointInTimeRecoveryEnabled: true
    ipConfiguration:
      ipv4Enabled: false  # No public IP address
      privateNetworkRef: 
        external: "{{ .Values.gcp.network }}"
        