apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/project-id : "{{ .Values.gcp.project }}"
  name: "{{ .Values.gcp.postgresql_user}}"
spec:
  instanceRef:
    name: "{{ .Values.gcp.postgresql_name }}"
  password:
    valueFrom:
      secretKeyRef:
        key: "postgresql-password"
        name: "postgresql"
