replicaCount: 1

image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu-gateway
  pullPolicy: Always
  tag: master-latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

redisPort: 6379

ingress:
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt"
  }
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]
  
resources: {}

