replicaCount: 1

image:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu-gateway
  pullPolicy: Always
  tag: master-latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

redisPort: 6379

disable_auth: false

sfuCapacity:
  max_sfu_load: 500
  num_scheduled_students: 25
  num_scheduled_teachers: 3
  remove_old_entries_probability: 1000


ingress:
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt"
  }
  hosts: {
  }
  tls: [
      endpoint: {
        hosts: [
          "vn-bfc.dev.kidsloop.net"
        ],
        secretName: "letsencrypt-vn-bfc.dev.kidsloop.net"
      }
  ]
  
resources: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80