kind: Service
apiVersion: v1
metadata:
  name: media-storage-external-svc
spec:
  type: ExternalName
  externalName: {{ .Values.externalServices.externalName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 443
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
