apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: media-storage-external-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/cluster-issuer: "letsencrypt"
    # Rewrite/Proxy annotations - see here: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.externalServices.serviceProtocol }}
    # https://github.com/kubernetes/ingress-nginx/issues/1600
    nginx.ingress.kubernetes.io/proxy-ssl-name: {{ .Values.externalServices.externalName }}
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: {{ .Values.externalServices.externalName }}
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.externalServices.externalName }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_name  {{ .Values.externalServices.externalName }} ;
      proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3 ;
      proxy_ssl_server_name on ;
      proxy_ssl_session_reuse off ;

# --v=5  - set nginx to debug mode...
spec:
  tls:
    - hosts:
      - cms{{ .Values.domain }}
      secretName: {{ .Values.secretName }}

  rules:
    - host: cms{{ .Values.domain }}
      http:
        paths:
        - path: /image/
          pathType: Prefix
          backend:
            serviceName: media-storage-external-svc
            servicePort: 443
        - path: /audio/
          pathType: Prefix
          backend:
            serviceName: media-storage-external-svc
            servicePort: 443
