apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-sfu-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-sfu-manager
subjects:
  - kind: ServiceAccount
    name: restart-sfu-manager
    namespace: {{ .Release.Namespace }}