apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sfu-manager-cronjob
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sfu-manager-cronjob
subjects:
  - kind: ServiceAccount
    name: sfu-manager-cronjob
    namespace: {{ .Release.Namespace }}