apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kl2.fullname" . }}
  labels:
    {{- include "kl2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kl2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kl2.selectorLabels" . | nindent 8 }}
        redis-client: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kl2-configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if eq .Values.provider "gcp" }}
      - name: cloud-sql-proxy-init
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.db_instance }}=tcp:{{ .Values.configuration.db_port }}"
        securityContext:
          runAsNonRoot: true  
      {{- end }}
      
      - name: {{ .Chart.Name }}-init
        image: flyway/flyway:latest
        args:
          - "migrate"
          - "-user=$(db_username)"
          {{- if eq .Values.provider "gcp" }}
          - "-url=jdbc:mysql://localhost:$(db_port)/$(db_name)"
          {{- else }}
          - "-url=jdbc:mysql://$(db_host):$(db_port)/$(db_name)"
          {{- end}}
          - "-password=$(MYSQL_PASSWORD)"
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
        envFrom:
          - configMapRef:
              name: {{ include "kl2.fullname" . }}-cm
        volumeMounts:
          - name: sql-migration
            mountPath: /flyway/sql
      
      containers:
      - name: {{ .Chart.Name }}
        command: [ "sh", "-c" ]
        args:
        {{- if eq .Values.provider "gcp" }}
        - |
          export connection_string="$(db_username):$(MYSQL_PASSWORD)@tcp(localhost:$(db_port))/$(db_name)?$(db_options)"
          ./handler
        {{- else }}
        - |
          export connection_string="$(db_username):$(MYSQL_PASSWORD)@tcp($(db_hostname):$(db_port))/$(db_name)?$(db_options)"
          ./handler
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8088
        envFrom:
          - configMapRef:
              name: {{ include "kl2.fullname" . }}-cm
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
        {{ if .Values.storage_endpoint }}
        volumeMounts:
          - name: s3-bucket-secret
            mountPath: /root/.aws
            readOnly: true
        {{ end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

      {{- if eq .Values.provider "gcp" }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.db_instance }}=tcp:{{ .Values.configuration.db_port }}"
        securityContext:
          runAsNonRoot: true  
      {{- end }}

      volumes:
        - name: sql-migration
          configMap:
            name: {{ include "kl2.fullname" . }}-sql-cm
        {{ if .Values.storage_endpoint }}
        - name: s3-bucket-secret
          secret:
            secretName: {{ include "kl2.fullname" . }}-s3-secret
        {{ end }}
        
      {{- if eq .Values.provider "gcp" }}
      serviceAccountName: cloudsql-proxy
      {{- end }}

