apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kl2.fullname" . }}
  labels:
    {{- include "kl2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kl2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kl2.selectorLabels" . | nindent 8 }}
        redis-client: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kl2-configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: flyway/flyway:latest
        args:
          - "migrate"
          - "-user=kidsloop2"
          - "-url=jdbc:mysql://localhost:3306/kidsloop2"
          - "-password=$(MYSQL_PASSWORD)"
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
        volumeMounts:
          - name: sql-migration
            mountPath: /flyway/sql
      containers:
      - name: {{ .Chart.Name }}
        command: [ "sh", "-c" ]
        args:
        - |
          export connection_string=$(echo $connection_string | sed "s/xxxxxx/$MYSQL_PASSWORD/g")
          ./handler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8088
        envFrom:
          - configMapRef:
              name: {{ include "kl2.fullname" . }}-cm
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: sql-migration
          configMap:
            name: {{ include "kl2.fullname" . }}-sql-cm

