image:
  repository: 494634321140.dkr.ecr.ap-northeast-2.amazonaws.com/vietnam-ecr-token
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

ecrTokenSecret: "ecr-registry"
awsCredentialsSecret: "aws-credentials"
refreshSchedule: '0 */6 * * *'

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
