apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nightwatch.fullname" . }}
  labels:
    {{- include "nightwatch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nightwatch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nightwatch.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}      
      containers:
      - name: {{ .Chart.Name }}-teacher      
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"       
        env:
          - name: GROUPNAME
            value: "teacher"
          - name: ROOMID
            value: "{{ .Values.room_id }}"            
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      - name: {{ .Chart.Name }}-student      
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"       
        env:
          - name: GROUPNAME
            value: "student"
          - name: ROOMID
            value: "{{ .Values.room_id }}"            
        resources:
          {{- toYaml .Values.resources | nindent 12 }}          