apiVersion: v1
kind: Service
metadata:
  name: {{ include "onboarding_scheduling.fullname" . }}-svc
  labels:
    {{- include "onboarding_scheduling.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "onboarding_scheduling.selectorLabels" . | nindent 4 }}
  type: {{ .Values.serviceType }}
