replicaCount: 1

image:
  repository: 494634321140.dkr.ecr.ap-northeast-2.amazonaws.com/vietnam-sfu-manager
  pullPolicy: Always
  tag: latest

sfuImage:
  repository: 494634321140.dkr.ecr.ap-northeast-2.amazonaws.com/vietnam-sfu
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

hostNetworking: false
redisHost: redis-master.persistence.svc
redisPort: 6379

resources: {}

sfuManagerConfiguration:
  job: "/etc/vietnam-sfu-manager/job.yaml"
  desiredPodsGetter: "prometheus"
  pods: 6
  promDesiredAvailable: 6
  promHost: "http://example.com"
  promAvailableQuery: 'min(sfuCount{type="available"})'
  promTotalQuery: 'max(sfuCount{type="total"})'
