replicaCount: 1

sfuManagerImage:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu-manager
  pullPolicy: Always
  tag: master-latest

sfuImage:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu
  pullPolicy: Always
  tag: master-latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

hostNetworking: false
usePodIp: false  # Used to get sfu-gateway > sfu instance IP resolution working (with .status.ip ) in GCP RK deployment
redisPort: 6379

resources: {}

sfuManagerConfiguration:
  job: "/etc/sfu-manager/job.yaml"
  desiredPodsGetter: "prometheus"
  pods: 2
  promDesiredAvailable: 2
  promHost: "http://example.com"
  promAvailableQuery: 'min(sfuCount{type="available"})'
  promTotalQuery: 'max(sfuCount{type="total"})'
