nameOverride: ""
fullnameOverride: ""
replicaCount: 1
imagePullSecrets: []

sfuManagerImage:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu-manager
  pullPolicy: Always
  tag: master-latest

sfuImage:
  repository: 942095822719.dkr.ecr.eu-west-2.amazonaws.com/kidsloop-sfu
  pullPolicy: Always
  tag: master-latest


redisHost: TODO
redisPort: 6379

hostNetworking: false
usePodIpAsHostnameOverride: false
useIp: false

resources: {}

provider: "aws"

nodegroupSelector: {"nodegroup": "public"}

sfuManagerConfiguration:
  job: "/etc/sfu-manager/job.yaml"
  desiredPodsGetter: "prometheus"
  pods: 2
  promDesiredAvailable: 2
  promHost: "http://example.com"
  promAvailableQuery: 'min(sfuCount{type="available"})'
  promTotalQuery: 'max(sfuCount{type="total"})'
