apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "assessment.fullname" . }}
  labels:
    {{- include "assessment.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "assessment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "assessment.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        startupProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: USE_ATTENDANCE_API_FLAG
            value: "1"
          - name: CMS_API_URL
            value: {{ .Values.cmsApiUrl }}
          - name: USER_SERVICE_ENDPOINT
            value: {{ .Values.userServiceEndpoint }}
          - name: ATTENDANCE_SERVICE_ENDPOINT
            value: {{ .Values.attendanceServiceEndpoint }}
          - name: USE_XAPI_SQL_DATABASE_FLAG
            value: "1"
          - name: ROUTE_PREFIX
            value: "/assessment"
          - name: USER_SERVICE_API_URL
            value: {{ .Values.user_api_endpoint }}
          - name: CMS_DB_SECRET
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
          - name: CMS_DATABASE_URL
            value: "mysql://{{ .Values.cms_db_user }}:$(CMS_DB_SECRET)@{{ .Values.mysql_host }}:3306/{{ .Values.cms_db }}"
          - name: POSTGRES_DB_SECRET
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          - name: USER_DATABASE_URL
            value: "postgres://{{ .Values.postgresql_username }}:$(POSTGRES_DB_SECRET)@{{ .Values.postgresql_host }}/{{ .Values.postgresql_database }}"
          - name: ASSESSMENT_DATABASE_URL
            value: "postgres://{{ .Values.postgresql_username }}:$(POSTGRES_DB_SECRET)@{{ .Values.postgresql_host }}/{{ .Values.postgresql_assessment_database }}"
          - name: ATTENDANCE_DATABASE_URL
            value: "postgres://{{ .Values.postgresql_username }}:$(POSTGRES_DB_SECRET)@{{ .Values.postgresql_host }}/{{ .Values.postgresql_attendance_database }}"
          - name: XAPI_DATABASE_URL
            value: "postgres://{{ .Values.postgresql_username }}:$(POSTGRES_DB_SECRET)@{{ .Values.postgresql_xapi_host }}/{{ .Values.postgresql_xapi_database }}"
          - name: AWS_REGION
            value: {{ .Values.aws_region }}
          - name: NEW_RELIC_NO_CONFIG_FILE
            value: "true"
          - name: NEW_RELIC_APP_NAME
            value: {{ include "assessment.fullname" . }}_{{  .Values.deployment_name }}
          - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            value: "true"
          - name: NEW_RELIC_LABELS
            value: Deployment:{{  .Values.deployment_name }};Region:{{  .Values.deployment_region }};Environment:{{  .Values.deploument_env }};Version:{{  .Values.image.tag }};Component:{{ include "assessment.fullname" . }}
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic-apikey-secret
                key: NEW_RELIC_LICENSE_KEY
        volumeMounts:
          - name: xapi-dynamodb-secret
            mountPath: /root/.aws
            readOnly: true  
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq .Values.provider "gcp" }}
      - name: postgres-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.postgresql_instance }}=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          {{- toYaml .Values.sqlProxy.resources | nindent 12 }}
      - name: mysql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.mysql_instance }}=tcp:3306"
        securityContext:
          runAsNonRoot: true
        resources:
          {{- toYaml .Values.sqlProxy.resources | nindent 12 }}
      serviceAccountName: cloudsql-proxy 
      {{- end }}
      volumes:
        - name: xapi-dynamodb-secret
          secret:
            secretName: xapi-dynamodb-secret
