apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-backend.fullname" . }}
  labels:
    {{- include "auth-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "auth-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-backend.selectorLabels" . | nindent 8 }}
        redis-client: "true"
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        env:
        - name: DOMAIN
          value: {{ .Values.domain }}
        - name: PORT
          value: "8080"
        - name: JWT_ISSUER
          value: "kidsloop"
        - name: JWT_ACCESS_TOKEN_DURATION
          value: "900"
        - name: JWT_REFRESH_TOKEN_DURATION
          value: "1206000"
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: auth-jwt-credentials
              key: jwt-algorithm
        - name: JWT_PRIVATE_KEY_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: auth-jwt-credentials
              key: jwt_private_passphrase
        - name: JWT_PRIVATE_KEY_FILENAME
          value: /key/private_key
        - name: JWT_PUBLIC_KEY_FILENAME
          value: /key/public_key
        - name: DB_SECRET
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgresql-password
        - name: DATABASE_URL
          value: "postgres://{{ .Values.postgresql_username }}:$(DB_SECRET)@{{ .Values.postgresql_host }}/{{ .Values.postgresql_database }}"
        volumeMounts:
          - name: auth-jwt-credentials
            mountPath: /key
            readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq .Values.provider "gcp" }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.postgresql_instance }}=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          {{- toYaml .Values.sqlProxy.resources | nindent 12 }}
      {{- end }}
      volumes:
        - name: auth-jwt-credentials
          secret:
            secretName: auth-jwt-credentials
      {{- if eq .Values.provider "gcp" }}
      serviceAccountName: cloudsql-proxy
      {{- end }}
