apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kl2.fullname" . }}
  labels:
    {{- include "kl2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kl2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kl2.selectorLabels" . | nindent 8 }}
        redis-client: "true"
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8088
        envFrom:
          - configMapRef:
              name: {{ include "kl2.fullname" . }}-cm
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

