{{- if .Values.database.connectionString.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.connectionString.value }}
{{- end }}
