apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user_service.fullname" . }}
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user_service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user_service.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodegroupSelector | nindent 12 }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        ports:
          - name: http
            protocol: TCP
            containerPort: {{ .Values.userService.port }}
        env:
          - name: NODE_ENV
            value: "{{ .Values.userService.nodeEnv }}"
          - name: DOMAIN
            value: {{ .Values.domain }}
          - name: PORT
            value: "{{ .Values.userService.port }}"
          - name: ROUTE_PREFIX
            value: "{{ .Values.userService.routePrefix }}"
          {{- if .Values.database.connectionString.existingSecret }}
          - name: DATABASE_URL
            valueFrom:
              {{- with .Values.database.connectionString.existingSecret }}
              secretKeyRef:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- else if .Values.database.connectionString.value }}
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgres
                key: database-url
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      
      {{- if eq .Values.provider "gcp" }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.postgresql_instance }}=tcp:5432"
        securityContext:
          runAsNonRoot: true  
      {{- end }}

      {{- if eq .Values.provider "gcp" }}
      serviceAccountName: cloudsql-proxy
      {{- end }}

