apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user_service.fullname" . }}
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "user_service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user_service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        startupProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: LOG_LEVEL
            value: "info"
          - name: ENABLE_PAGE_DOCS
            value: "1"
          - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            value: "true"
          - name: LOG_STYLE
            value: "NEW_RELIC"
          - name: NODE_ENV
            value: "{{  .Values.deployment_env }}"
          - name: DOMAIN
            value: {{ .Values.domain }}
          - name: PORT
            value: "8080"
          - name: ROUTE_PREFIX
            value: "/user"
          - name: DB_SECRET
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgresql-password
          - name: DATABASE_URL
            value: "postgres://{{ .Values.postgresql_username }}:$(DB_SECRET)@{{ .Values.postgresql_host }}/{{ .Values.postgresql_database }}"
          - name: STORAGE_BUCKET
            value: {{ .Values.whitelabel_storage_bucket }}
          - name: STORAGE_PROVIDER
            value: {{ .Values.whitelabel_storage_provider }}
          {{ if .Values.storage_endpoint }}
          - name: FORCE_LOCAL_STORAGE
            value: "{{ .Values.whitelabel_force_local_storage }}"
          - name: STORAGE_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: user-s3-secret
                key: aws_access_key_id
          - name: STORAGE_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: user-s3-secret
                key: secret_access_key
          - name: STORAGE_REGION
            value: {{ .Values.region }}
          - name: STORAGE_ENDPOINT
            value: {{ .Values.storage_endpoint }}
          {{ end }}
          - name: STORAGE_PROJECT_ID
            value: {{ .Values.project }}
          - name: NEW_RELIC_NO_CONFIG_FILE
            value: "true"
          - name: NEW_RELIC_APP_NAME
            value: {{ include "user_service.fullname" . }}_{{  .Values.deployment_name }}
          - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            value: "true"
          - name: NEW_RELIC_LABELS
            value: Deployment:{{  .Values.deployment_name }};Region:{{  .Values.deployment_region }};Environment:{{  .Values.deployment_env }};Version:{{  .Values.image.tag }};Component:{{ include "user_service.fullname" . }}
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic-apikey-secret
                key: NEW_RELIC_LICENSE_KEY
        {{- if eq .Values.provider "gcp" }}
          - name: STORAGE_GOOGLE_KEY_FILE_NAME
            value: /key/key.json
        volumeMounts:
          - name: whitelabel-storage-sa-key
            mountPath: /key
            readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      
      {{- if eq .Values.provider "gcp" }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.postgresql_instance }}=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          {{- toYaml .Values.sqlProxy.resources | nindent 12 }}
      serviceAccountName: cloudsql-proxy
      volumes:
        - name: whitelabel-storage-sa-key
          secret:
            secretName: whitelabel-bucket
      {{- end }}