environments:
  indonesia-staging:
    values:
      - ../../env/indonesia-staging/.env.yaml
  indonesia-production:
    values:
      - ../../env/indonesia-production/.env.yaml
  indonesia-rk-prod:
    values:
      - ../../env/indonesia-rk-prod/.env.yaml
  indonesia-rk-beta:
    values:
      - ../../env/indonesia-rk-beta/.env.yaml

releases:

  - name: gke-redis
    namespace: config-connector
    chart: charts/redis
    values:
      - gcp:
          region: {{ .Values.terraform_region }}
          network: {{ .Values.terraform_vpc.value }}
          project: {{ .Values.terraform_project }}
          redis_name: {{ .Values.gcp.redis.name }}
          redis_display_name: {{ .Values.gcp.redis.display_name }}
          redis_version: {{ .Values.gcp.redis.version }}
          redis_memory_size: {{ .Values.gcp.redis.memory_size }}
          redis_tier: {{ .Values.gcp.redis.tier }}


  - name: cloudsql-proxy
    namespace: {{ .Environment.Values.k8s_namespace_kidsloop }}
    chart: charts/cloud-sql-proxy


  - name: gke-mysql
    namespace: config-connector
    chart: charts/mysql
    values:
      - gcp:
          region: {{ .Values.terraform_region }}
          network: {{ .Values.terraform_vpc.value }}
          project: {{ .Values.terraform_project }}
          mysql_name: {{ .Values.gcp.mysql.name }}
          mysql_version: {{ .Values.gcp.mysql.version }}
          mysql_tier: {{ .Values.gcp.mysql.tier }}
          mysql_charset: {{ .Values.gcp.mysql.charset }}
          mysql_collation: {{ .Values.gcp.mysql.collation }}
          mysql_disk_size: {{ .Values.gcp.mysql.disk.size }}
          mysql_disk_type: {{ .Values.gcp.mysql.disk.type }}
          mysql_user: {{ .Values.gcp.mysql.user }}

  - name: mysql-assessment-user
    namespace: config-connector
    chart: charts/mysql-user
    values:
      - gcp:
          project: {{ .Values.terraform_project }}
          mysql_name: {{ .Values.gcp.mysql.name }}
          mysql_user: {{ .Values.gcp.mysql.assessment_user }}

  - name: gke-mysql-sql-proxy
    namespace: {{ .Environment.Values.k8s_namespace_kidsloop }}
    chart: charts/mysql-sql-proxy
    values:
      - gcp:
          region: {{ .Environment.Values.terraform_region }}
          project: {{ .Environment.Values.terraform_project }}
          mysql_name: {{ .Environment.Values.gcp.mysql.name }}
    needs:
      - config-connector/gke-mysql
      - {{ .Environment.Values.k8s_namespace_kidsloop }}/cloudsql-proxy

  - name: gke-postgresql
    namespace: config-connector
    chart: charts/postgresql
    values:
      - gcp:
          region: {{ .Values.terraform_region }}
          network: {{ .Values.terraform_vpc.value }}
          project: {{ .Values.terraform_project }}
          postgresql_name: {{ .Values.gcp.postgresql.name }}
          postgresql_version: {{ .Values.gcp.postgresql.version }}
          postgresql_tier: {{ .Values.gcp.postgresql.tier }}
          postgresql_charset: {{ .Values.gcp.postgresql.charset }}
          postgresql_collation: {{ .Values.gcp.postgresql.collation }}
          postgresql_disk_size: {{ .Values.gcp.postgresql.disk.size }}
          postgresql_disk_type: {{ .Values.gcp.postgresql.disk.type }}
          postgresql_user: {{ .Values.gcp.postgresql.user }}

  - name: gke-postgres-sql-proxy
    namespace: {{ .Environment.Values.k8s_namespace_kidsloop }}
    chart: charts/postgres-sql-proxy
    values:
      - gcp:
          region: {{ .Environment.Values.terraform_region }}
          project: {{ .Environment.Values.terraform_project }}
          postgresql_name: {{ .Environment.Values.gcp.postgresql.name }}
    needs:
      - config-connector/gke-postgresql
      - {{ .Environment.Values.k8s_namespace_kidsloop }}/cloudsql-proxy

  - name: gke-postgresql-db-assessment
    namespace: config-connector
    chart: charts/postgresql-db
    values:
      - gcp:
          project: {{ .Values.terraform_project }}
          postgresql_name: {{ .Values.gcp.postgresql.name }}
          postgresql_db_name: {{ .Values.gcp.postgresql.assessment_database }}
          postgresql_charset: {{ .Values.gcp.postgresql.charset }}
          postgresql_collation: {{ .Values.gcp.postgresql.collation }}

  - name: gke-postgresql-db-xapi
    namespace: config-connector
    chart: charts/postgresql-db
    values:
      - gcp:
          project: {{ .Values.terraform_project }}
          postgresql_name: {{ .Values.gcp.postgresql.name }}
          postgresql_db_name: {{ .Values.gcp.postgresql.xapi_database }}
          postgresql_charset: {{ .Values.gcp.postgresql.charset }}
          postgresql_collation: {{ .Values.gcp.postgresql.collation }}
          
  - name: gke-ingress-support
    namespace: config-connector
    chart: charts/ingress-support
    values:
      - gcp:
          project: {{ .Values.terraform_project }}
          compute_address_name: ingress-https-load-balancer