environments:
  indonesia-staging:
    values:
      - ../../env/indonesia-staging/.env.yaml
  oc:
    values:
      - ../../env/oc/.env.yaml
      
releases:

  - name: gke-redis
    namespace: config-connector
    chart: charts/redis
    values:
      - gcp:
          region: {{ .Environment.Values.terraform_region }}
          network: {{ .Environment.Values.terraform_vpc.value }}
          project: {{ .Environment.Values.terraform_project }}
          redis_name: {{ .Environment.Values.gcp.redis.name }}
          redis_display_name: {{ .Environment.Values.gcp.redis.display_name }}
          redis_version: {{ .Environment.Values.gcp.redis.version }}
          redis_memory_size: {{ .Environment.Values.gcp.redis.memory_size }}
          redis_tier: {{ .Environment.Values.gcp.redis.tier }}

  - name: gke-mysql
    namespace: config-connector
    chart: charts/mysql
    values:
      - gcp:
          region: {{ .Environment.Values.terraform_region }}
          network: {{ .Environment.Values.terraform_vpc.value }}
          project: {{ .Environment.Values.terraform_project }}
          mysql_name: {{ .Environment.Values.gcp.mysql.name }}
          mysql_version: {{ .Environment.Values.gcp.mysql.version }}
          mysql_tier: {{ .Environment.Values.gcp.mysql.tier }}
          mysql_charset: {{ .Environment.Values.gcp.mysql.charset }}
          mysql_collation: {{ .Environment.Values.gcp.mysql.collation }}
          mysql_disk_size: {{ .Environment.Values.gcp.mysql.disk.size }}
          mysql_disk_type: {{ .Environment.Values.gcp.mysql.disk.type }}
          mysql_user: {{ .Environment.Values.gcp.mysql.user }}

  - name: gke-postgresql
    namespace: config-connector
    chart: charts/postgresql
    values:
      - gcp:
          region: {{ .Environment.Values.terraform_region }}
          network: {{ .Environment.Values.terraform_vpc.value }}
          project: {{ .Environment.Values.terraform_project }}
          postgresql_name: {{ .Environment.Values.gcp.postgresql.name }}
          postgresql_version: {{ .Environment.Values.gcp.postgresql.version }}
          postgresql_tier: {{ .Environment.Values.gcp.postgresql.tier }}
          postgresql_charset: {{ .Environment.Values.gcp.postgresql.charset }}
          postgresql_collation: {{ .Environment.Values.gcp.postgresql.collation }}
          postgresql_disk_size: {{ .Environment.Values.gcp.postgresql.disk.size }}
          postgresql_disk_type: {{ .Environment.Values.gcp.postgresql.disk.type }}
          postgresql_user: {{ .Environment.Values.gcp.postgresql.user }}

  - name: gke-service-kl2-static
    namespace: config-connector
    chart: charts/service-kl2-static
    values:
      - gcp:
          region: {{ .Environment.Values.terraform_region }}
          project: {{ .Environment.Values.terraform_project }}
          