{{- if .Values.externalServices.h5p.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-h5p-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/cluster-issuer: "letsencrypt"
    # Rewrite/Proxy annotations - see here: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.externalServices.h5p.serviceProtocol }}
    # https://github.com/kubernetes/ingress-nginx/issues/1600
{{- if .Values.externalServices.h5p.externalName }}
    nginx.ingress.kubernetes.io/proxy-ssl-name: {{ .Values.externalServices.h5p.externalName }}
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: {{ .Values.externalServices.h5p.externalName }}
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.externalServices.h5p.externalName }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_name  {{ .Values.externalServices.h5p.externalName }} ;
      proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3 ;
      proxy_ssl_server_name on ;
      proxy_ssl_session_reuse off ;
{{- else }}
    nginx.ingress.kubernetes.io/proxy-ssl-name: h5p{{ .Values.domain }}
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: h5p{{ .Values.domain }}
    nginx.ingress.kubernetes.io/upstream-vhost: h5p{{ .Values.domain }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_name  h5p{{ .Values.domain }} ;
      proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3 ;
      proxy_ssl_server_name on ;
      proxy_ssl_session_reuse off ;
{{- end }}

# --v=5  - set nginx to debug mode...
spec:
  tls:
    - hosts:
      - live{{ .Values.domain }}
      secretName: tls-secret

  rules:
    - host: live{{ .Values.domain }}
      http:
        paths:
        - path: /h5p/
          pathType: Prefix
          backend:
            service:
              name: external-h5p-svc
              port:
                number: {{ .Values.externalServices.h5p.servicePort }}
    - host: h5p{{ .Values.domain }}
      http:
        paths:
        - path: /h5p/
          pathType: Prefix
          backend:
            service:
              name: external-h5p-svc
              port:
                number: {{ .Values.externalServices.h5p.servicePort }}
{{- end }}
