apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployments-scaling{{.Values.suffix}}-role
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name  }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "delete", "patch", "create"]