repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  
environments:
  default:
    values:
      - host: vn-bfc.dev.kidsloop.net

releases:

  - name: redis
    namespace: persistence
    chart: bitnami/redis
    version: ~11.3.4
    values:
      - cluster:
          slaveCount: 3
      - metrics:
          enabled: true
      - usePassword: false
      - slave:
          persistence:
            enabled: false
      - master:
          persistence:
            enabled: false
      - networkPolicy:
          enabled: true
          ingressNSMatchLabels:
            redis-namespace: "true"
          ingressNSPodMatchLabels:
            redis-client: "true"

  - name: postgresql-ha
    namespace: persistence
    chart: bitnami/postgresql-ha
    values:
      - global:
          storageClass: premium-hdd
          postgresql:
            existingSecret: postgresql
            #username: kidsloop
            database: kidsloop
      - persistence:
          size: 8Gi
          storageClass: premium-hdd
      - pgpool:
          enabled: true
          replicaCount: 2
      - initdbScripts:
          db-init.sql: |
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
            CREATE EXTENSION IF NOT EXISTS "pgcrypto";
            CREATE EXTENSION IF NOT EXISTS "pg_trgm";

  - name: mysql
    namespace: persistance
    chart: bitnami/mysql
    version: ~8.0.0
    values:
      - architecture: replication
      - metrics:
          enabled: true
      - primary:
          persistence:
            size: 8Gi
            storageClass: premium-hdd
      - secondary:
          replicaCount: 2
          persistence:
            size: 8Gi
            storageClass: premium-hdd
      - resources:
          limits:
            memory: 256Mi
            cpu: 250m
          requests:
            memory: 256Mi
            cpu: 250m

