apiVersion: v1
kind: Service
metadata:
  name: {{ include "external.fullname" . }}-svc
  labels:
    {{- include "external.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalName }}
