apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-frontend.fullname" . }}-svc
  labels:
    {{- include "auth-frontend.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "auth-frontend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.serviceType }}
