{{- if .Values.database.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cms-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-password: {{ .Values.database.password.value }}
{{- end }}

---

{{- if .Values.redis.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-password: {{ .Values.redis.password.value }}
{{- end }}

