apiVersion: v1
kind: Service
metadata:
  name: {{ include "cms-backend.fullname" . }}-svc
  labels:
    {{- include "cms-backend.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    {{- include "cms-backend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.serviceType }}
