apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cms-backend.fullname" . }}
  labels:
    {{- include "cms-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cms-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cms-backend.selectorLabels" . | nindent 8 }}
        redis-client: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cms-backend-configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    
      containers:
      - name: {{ .Chart.Name }}
        command: [ "sh", "-c" ]
        args:
        {{- if eq .Values.provider "gcp" }}
        - |
          export connection_string="$(db_username):$(MYSQL_PASSWORD)@tcp(localhost:$(db_port))/$(db_name)?$(db_options)"
          ./handler
        {{- else }}
        - |
          export connection_string="$(db_username):$(MYSQL_PASSWORD)@tcp($(db_hostname):$(db_port))/$(db_name)?$(db_options)"
          ./handler
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8088
        envFrom:
          - configMapRef:
              name: {{ include "cms-backend.fullname" . }}-cm
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
        {{ if .Values.configuration.storage_endpoint }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cms-backend-s3-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cms-backend-s3-secret
                key: secret_access_key
        {{ end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

      {{- if eq .Values.provider "gcp" }}
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances={{ .Values.project }}:{{ .Values.region }}:{{ .Values.mysql_instance }}=tcp:{{ .Values.configuration.db_port }}"
        securityContext:
          runAsNonRoot: true  
      {{- end }}

      volumes:
        - name: sql-migration
          configMap:
            name: {{ include "cms-backend.fullname" . }}-sql-cm
        {{ if .Values.configuration.storage_endpoint }}
        - name: s3-bucket-secret
          secret:
            secretName: {{ include "cms-backend.fullname" . }}-s3-secret
        {{ end }}
        
      {{- if eq .Values.provider "gcp" }}
      serviceAccountName: cloudsql-proxy
      {{- end }}

