timeoutSec: 3600  # Need long timeout to support websockets
cdn:
  enabled: false
connectionDraining:
  drainingTimeoutSec: 3600     # Need long timeout to support websockets
healthCheck:
  requestPath: /
  type: HTTP
  port: 80
  checkIntervalSec: 15
  timeoutSec: 15
  healthyThreshold: 1
  unhealthyThreshold: 2
