{{- if .Values.prometheus_enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pdf-service.fullname" . }}-sm
  labels:
    {{- include "pdf-service.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
 {{- end }}