{{- if eq .Values.provider "vngcloud" }}

apiVersion: v1
kind: ConfigMap
metadata:
  # name: {{ include "spr_api.fullname" . }}-nginx-ingress-cm
  # TODO find a future-proof way to associate this ConfigMap with the VNGCloud-provisioned ingress-nginx-controller
  # such that we don't have to hard-code the ingress-nginx-controller release name (`magnum` in this case)
  name: magnum-nginx-ingress-controller
  namespace: kube-system
  labels:
    {{- include "spr_api.nginxIngressConfigMapLabels" . | nindent 4 }}
data:
  http-snippet: |
    map $http_origin $allowed_origin {
      default you_shall_not_pass; # this is not a joke
      # matching e.g. https://*.alpha.kidsloop.vn, https://*.beta.kidsloop.vn, or https://*.kidsloop.vn
      # matching e.g. https://*.alpha.kidsloop.net, https://*.beta.kidsloop.net, or https://*.kidsloop.net
      ~^https://.*\.kidsloop\.vn$ ~^https://.*\.kidsloop\.net$ $http_origin;
    }

{{- end }}
