apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfu.fullname" . }}-manager
  labels:
    {{- include "sfu-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfu-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sfu-manager.selectorLabels" . | nindent 8 }}
        redis-client: "true"
    spec:
      serviceAccountName: {{ include "sfu.fullname" . }}-serviceaccount
      {{- with .Values.sfuManagerImage.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.sfuManagerImage.repository }}:{{ .Values.sfuManagerImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.sfuManagerImage.pullPolicy }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config
          mountPath: /etc/sfu-manager
      volumes:
      - name: config
        configMap:
          name: {{ include "sfu.fullname" . }}-cm
