apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfu.fullname" . }}-manager
  labels:
    {{- include "sfu-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfu-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sfu-manager.selectorLabels" . | nindent 8 }}
        redis-client: "true"
    spec:
      serviceAccountName: {{ include "sfu.fullname" . }}-serviceaccount
      {{- with .Values.sfuManagerImage.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.sfuManagerImage.repository }}:{{ .Values.sfuManagerImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.sfuManagerImage.pullPolicy }}"
        resources:
          {{- toYaml .Values.sfuManagerResources | nindent 12 }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NEW_RELIC_NO_CONFIG_FILE
            value: "true"
          - name: NEW_RELIC_APP_NAME
            value: {{ include "sfu.fullname" . }}-manager_{{  .Values.deployment_name }}
          - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
            value: "true"
          - name: NEW_RELIC_LABELS
            value: Deployment:{{  .Values.deployment_name }};Region:{{  .Values.deployment_region }};Environment:{{  .Values.deployment_env }};Version:{{ .Values.sfuManagerImage.tag | default .Chart.AppVersion }};Component:{{ include "sfu.fullname" . }}-manager
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic-apikey-secret
                key: NEW_RELIC_LICENSE_KEY
        volumeMounts:
        # This appears to have no effect
        - name: config
          mountPath: /etc/sfu-manager

        # Mount only job.yaml again on the root path
        - name: config-jobconfig
          mountPath: /job.yaml
          subPath: job.yaml
      volumes:
      # This appears to have no effect
      - name: config
        configMap:
          name: {{ include "sfu.fullname" . }}-cm
      # Mount only job.yaml again on the root path
      - name: config-jobconfig
        configMap:
          name: {{ include "sfu.fullname" . }}-cm
          items:
          - key: job.yaml
            path: job.yaml
