apiVersion: v1
kind: Service
metadata:
  name: {{ include "sfu.fullname" . }}-manager
  labels:
    {{- include "sfu-manager.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "sfu-manager.selectorLabels" . | nindent 4 }}
  type: {{ .Values.serviceType }}
