apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sfu.fullname" . }}-role
  labels:
    {{- include "sfu.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
