apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfu.fullname" . }}
  labels:
    {{- include "sfu.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sfu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sfu.selectorLabels" . | nindent 8 }}
        redis-client: "true"
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        env:
          - name: NODE_ENV
            value: "beta"
          - name: PORT
            value: "8080"
          - name: REDIS_HOST
            value: {{ .Values.redisHost }}
          - name: REDIS_PORT
            value: {{ .Values.redisPort | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

