apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sfu-gateway.fullname" . }}
  labels:
    {{- include "sfu-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sfu-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sfu-gateway.selectorLabels" . | nindent 8 }}
        redis-client: "true"
    spec:
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        startupProbe:
          httpGet:
            path: /server-health
            port: http
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /server-health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /server-health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: DISABLE_AUTH
            value: {{ .Values.disable_auth | quote }}
          - name: MAX_SFU_LOAD
            value: {{ .Values.sfuCapacity.max_sfu_load | quote }}
          - name: NUM_SCHEDULED_STUDENTS
            value: {{ .Values.sfuCapacity.num_scheduled_students | quote }}
          - name: NUM_SCHEDULED_TEACHERS
            value: {{ .Values.sfuCapacity.num_scheduled_teachers | quote }}
          - name: REMOVE_OLD_ENTRIES_PROBABILITY
            value: {{ .Values.sfuCapacity.remove_old_entries_probability | quote }}        
          - name: CMS_ENDPOINT
            value: "https://cms.{{ .Values.kl_domain }}"
          - name: NODE_ENV
            value: "{{  .Values.deployment_env }}"
          - name: PORT
            value: "8080"
          - name: REDIS_HOST
            value: {{ .Values.redisHost }}
          - name: REDIS_PORT
            value: {{ .Values.redisPort | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

