apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-token-cronjob{{.Values.suffix}}
  labels: 
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name  }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-token-serviceaccount{{.Values.suffix}}
          imagePullSecrets:
            - name: {{.Values.image_pull_secret}}
          restartPolicy: OnFailure
          containers:
            - image: {{.Values.image}}
              imagePullPolicy: Always
              name: ecr-token
              env:
                - name: NAMESPACE
                  value: {{ .Release.Namespace }}
                - name: SECRET_NAME
                  value: {{.Values.secret_name}}                
                - name: CREDENTIAL_SECRET_NAME
                  value: {{.Values.credential_secret_name}} 
                - name: AWS_REGION
                  value: {{.Values.aws_region}}
                - name: AWS_ACCOUNT_ID
                  value: "{{.Values.aws_account_id}}"
  schedule: "0 */6 * * *"
