apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-token-rolebinding{{.Values.suffix}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-token-role{{.Values.suffix}}
subjects:
- kind: ServiceAccount
  name: ecr-token-serviceaccount{{.Values.suffix}}
  namespace: {{ .Release.Namespace }}
