apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-token-cronjob{{.Values.suffix}}
  labels: 
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name  }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-token-serviceaccount{{.Values.suffix}}
          imagePullSecrets:
            - name: ecr-registry{{.Values.suffix}}
          restartPolicy: OnFailure
          containers:
            - image: {{.Values.image}}
              imagePullPolicy: Always
              name: ecr-token
              env:
                - name: NAMESPACE
                  value: {{ .Release.Namespace }}
                - name: SECRET_NAME
                  value: ecr-registry{{.Values.suffix}}

  schedule: "0 */6 * * *"
